import Foundation

/// The bundled fallback, which is `launch/cairn.jsonl` as a node served it.
///
/// The file is generated by `scripts/site-snapshot.sh` and copied here so a
/// phone that has never been pointed at a node still shows a real settled
/// log — not mock data. Yukon's landing page labels its own leaderboard
/// SIMULATED; inventing one here would refute the pitch on the screen
/// making it. Every view that renders this says so.
public enum BundledSnapshot {
    public static func load() throws -> Snapshot {
        guard let url = Bundle.module.url(forResource: "snapshot", withExtension: "json") else {
            throw NodeError.shape("bundled snapshot.json is missing")
        }
        let data = try Data(contentsOf: url)
        return try decodeSnapshot(data)
    }
}

public func decodeSnapshot(_ data: Data) throws -> Snapshot {
    let decoder = JSONDecoder()
    do {
        return try decoder.decode(Snapshot.self, from: data)
    } catch {
        throw NodeError.shape("bundled snapshot is not the shape this reader expects: \(error)")
    }
}
