"""Certificate checker: a conforming pair for SHA-1.

Full SHA-1, all 80 steps, all 160 digest bits, from a chaining value nobody
chose. **This objective is not expected to settle**, and it is posted anyway,
for the same reason `examples/certicom-ecdlp/` posts ECCp-131: a research
network should carry one benchmark whose difficulty nobody local chose.

Published estimates for the identical-prefix attack run between 2^61 and
2^63 compressions. SHAttered (2017) paid it once, across a GPU cluster, over
months. Everything cheaper that is
published -- the two-block structure, the disturbance vectors, the speed-ups --
is public and does not move that exponent much.

The gap between this rung and the 64-step rung below it is where the field
actually is. A better disturbance vector, which `objective-dv-sha1.json`
pays for directly, is one of the few things that moves it.

# What is checked, exactly

Two hex messages of equal length, both beginning with the pinned prefix,
differing somewhere, whose digests are equal on all 160 bits. Nothing else.

Equal length is a requirement rather than an accident. A same-length collision
composes: H(m || x) = H(m' || x) for every x, because Merkle-Damgard feeds the
same chaining value into the same remaining blocks. Colliding pairs of
different lengths do not compose, and the property that makes a collision worth
paying for is exactly the one that survives being appended to.

# What this does NOT decide

Anything about method. A pair from a hand-built differential path, from
published tooling, or from a birthday search verifies identically -- which is
the property that makes an unreliable contributor safe to accept, and the
reason this network buys artifacts rather than effort.

It also decides nothing about SHA-1 in general: it decides one pair
against one pinned chaining value.

Cost is 2^61 to 2^63 compressions; this rung is not expected to settle.

# Provenance

Generated by `tools/build_pinned.py`; `--check` re-renders it and diffs. The
sha256 of this file is inside the objective's id, so the instance below IS part
of the objective's identity: nobody can retarget a funded bounty at an easier
prefix, and an edit forks the objective rather than rescoring work already
done against it.

Self-contained on purpose. `docs/verification.md` rule 4: a checker that reads
an unpinned file passes today and fails tomorrow at the same hash.
"""

# -- the pinned instance ----------------------------------------------------
#
# PREFIX is sha512 of the seed string below: 64 bytes, which is exactly one
# message block for this function. Derived and not chosen -- a funder who picks
# a prefix can pick one whose chaining value they have already attacked.
# Deriving it also puts every published collision for SHA-1 out of reach as
# a copy, since all of them start from the standard IV behind a prefix their
# own author chose.
PREFIX_SEED = "cairn hash-differential v1 sha1"
PREFIX = bytes.fromhex(
    "1ecbec76180ec6ce67582973d359adfa1b4f8e4d0ee1d47ab9b2375bde6c35ff"
    "d7171b852db685ffff8ee570af6db329df2b17e1f062a34eee3790a60dc9bded"
)
# Compression steps actually run.
# All of them -- the unmodified function.
STEPS = 80
# Leading digest bytes that must agree.
# All of them.
DIGEST_BYTES = 20
# The artifact is attacker-supplied and it is billing this node's CPU. A
# collision needs two blocks past the prefix, not sixty-four; the cap is
# generous and still bounds the check at a few thousand step functions.
MAX_MESSAGE_BYTES = 4096
# SHA-1's expansion rotates; SHA-0's does not.
ROTATE_EXPANSION = True
_CLAIM = "collision on all 160 digest bits"
_ENDIAN = "big"

_M32 = 0xFFFFFFFF


def _rotl(x, n):
    x &= _M32
    return ((x << n) | (x >> (32 - n))) & _M32


def _pad(message):
    """Merkle-Damgard padding, big-endian length. FIPS 180."""
    bits = (8 * len(message)) & ((1 << 64) - 1)
    padded = message + b"\x80"
    padded += b"\x00" * ((56 - len(padded) % 64) % 64)
    return padded + bits.to_bytes(8, "big")


_SHA_IV = (0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0)
_SHA_K = (0x5A827999, 0x6ED9EBA1, 0x8F1BBCDC, 0xCA62C1D6)


def _compress(state, block):
    w = [int.from_bytes(block[4 * i:4 * i + 4], "big") for i in range(16)]
    for i in range(16, STEPS):
        x = w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16]
        # The single bit of difference between SHA-0 and SHA-1, and the reason
        # one of these two objectives is a worked demonstration and the other
        # is an open bounty. See the disturbance-vector evaluators.
        w.append(_rotl(x, 1) if ROTATE_EXPANSION else x)
    a, b, c, d, e = state
    for i in range(STEPS):
        rnd = i // 20
        if rnd == 0:
            f = (b & c) | (~b & d)
        elif rnd == 2:
            f = (b & c) | (b & d) | (c & d)
        else:
            f = b ^ c ^ d
        t = (_rotl(a, 5) + (f & _M32) + e + _SHA_K[rnd] + w[i]) & _M32
        a, b, c, d, e = t, a, _rotl(b, 30), c, d
    return tuple((x + y) & _M32 for x, y in zip(state, (a, b, c, d, e)))


_IV = _SHA_IV


def _trace(message):
    """Chaining value after every block. The path is recomputed from here."""
    data = _pad(message)
    state = _IV
    chain = [state]
    for offset in range(0, len(data), 64):
        state = _compress(state, data[offset:offset + 64])
        chain.append(state)
    return chain


def _digest(chain):
    return b"".join(x.to_bytes(4, _ENDIAN) for x in chain[-1])


def _decode(value, field):
    if not isinstance(value, str) or not value:
        return None, "artifact.%s must be a non-empty lowercase hex string" % field
    # Length before content. The artifact is attacker-supplied and it is billing
    # this node's CPU, so the megabyte of hex that would be rejected anyway is
    # rejected before it is scanned and decoded rather than after.
    if len(value) > 2 * MAX_MESSAGE_BYTES:
        return None, (
            "artifact.%s may be at most %d hex characters; got %d"
            % (field, 2 * MAX_MESSAGE_BYTES, len(value))
        )
    if len(value) % 2:
        return None, "artifact.%s must have an even number of hex characters" % field
    if any(c not in "0123456789abcdef" for c in value):
        return None, "artifact.%s must be lowercase hex" % field
    return bytes.fromhex(value), None


def _path(left, right, chain_left, chain_right):
    """Describe the differential path the pair actually follows.

    Derived by recomputation, never read off a field the submitter filled in.
    An artifact carrying a path it does not follow is not a different verdict
    here, it is the same verdict with a different sentence attached -- which is
    the point: the pair is the claim, and the path is what the pair does.
    """
    words = [
        i for i in range(0, min(len(left), len(right)), 4)
        if left[i:i + 4] != right[i:i + 4]
    ]
    steps = [
        i for i, (x, y) in enumerate(zip(chain_left, chain_right)) if x != y
    ]
    if not steps:
        return "no block ever differs (%d message words differ)" % len(words)
    # Whether the pair is a true collision or only agrees on the compared
    # prefix is visible right here, in the last chaining value, so say which
    # rather than letting a truncated instance read as a full one.
    closed = chain_left[-1] == chain_right[-1]
    return (
        "%d message words differ, first at word %d; the chaining difference is "
        "nonzero after blocks %d..%d of %d, and %s"
        % (
            len(words), words[0] // 4, steps[0], steps[-1], len(chain_left) - 1,
            "zero from there on -- a collision in the full state"
            if closed else
            "still nonzero at the end, so the pair agrees on the compared "
            "digest prefix and not on the whole state",
        )
    )


def check(artifact):
    if not isinstance(artifact, dict):
        return False, "artifact must be an object"
    left, error = _decode(artifact.get("m"), "m")
    if error is not None:
        return False, error
    right, error = _decode(artifact.get("m_prime"), "m_prime")
    if error is not None:
        return False, error
    if left == right:
        return False, "m and m_prime are the same message; a hash collides with itself"
    if len(left) != len(right):
        return False, (
            "m and m_prime must have the same length; got %d and %d bytes"
            % (len(left), len(right))
        )
    if len(left) > MAX_MESSAGE_BYTES:
        return False, (
            "messages may be at most %d bytes; got %d"
            % (MAX_MESSAGE_BYTES, len(left))
        )
    if not left.startswith(PREFIX) or not right.startswith(PREFIX):
        return False, (
            "both messages must begin with the pinned %d-byte prefix"
            % len(PREFIX)
        )
    chain_left, chain_right = _trace(left), _trace(right)
    digest_left = _digest(chain_left)[:DIGEST_BYTES]
    digest_right = _digest(chain_right)[:DIGEST_BYTES]
    if digest_left != digest_right:
        differing = sum(
            bin(x ^ y).count("1") for x, y in zip(digest_left, digest_right)
        )
        return False, (
            "digests differ in %d of %d bits: %s vs %s"
            % (differing, 8 * DIGEST_BYTES, digest_left.hex(), digest_right.hex())
        )
    return True, "%s on %s: %s" % (
        _CLAIM, digest_left.hex(), _path(left, right, chain_left, chain_right)
    )
