"""Certificate checker: a conforming pair for MD5.

Full MD5, all 64 steps, all 128 digest bits, from a chaining value nobody
chose.

The identical-prefix attack works from an arbitrary chaining value and the
published implementations take a parameter for exactly that, so this rung is
minutes of compute for someone willing to run other people's code. That is a
statement about MD5 in 2026 and not a complaint about the bounty: the ladder
needs a rung where the cost is real, small, and known.

# What is checked, exactly

Two hex messages of equal length, both beginning with the pinned prefix,
differing somewhere, whose digests are equal on all 128 bits. Nothing else.

Equal length is a requirement rather than an accident. A same-length collision
composes: H(m || x) = H(m' || x) for every x, because Merkle-Damgard feeds the
same chaining value into the same remaining blocks. Colliding pairs of
different lengths do not compose, and the property that makes a collision worth
paying for is exactly the one that survives being appended to.

# What this does NOT decide

Anything about method. A pair from a hand-built differential path, from
published tooling, or from a birthday search verifies identically -- which is
the property that makes an unreliable contributor safe to accept, and the
reason this network buys artifacts rather than effort.

It also decides nothing about MD5 in general: it decides one pair
against one pinned chaining value.

Cost is roughly 2^16 to 2^24 MD5 computations with published tooling.

# Provenance

Generated by `tools/build_pinned.py`; `--check` re-renders it and diffs. The
sha256 of this file is inside the objective's id, so the instance below IS part
of the objective's identity: nobody can retarget a funded bounty at an easier
prefix, and an edit forks the objective rather than rescoring work already
done against it.

Self-contained on purpose. `docs/verification.md` rule 4: a checker that reads
an unpinned file passes today and fails tomorrow at the same hash.
"""

# -- the pinned instance ----------------------------------------------------
#
# PREFIX is sha512 of the seed string below: 64 bytes, which is exactly one
# message block for this function. Derived and not chosen -- a funder who picks
# a prefix can pick one whose chaining value they have already attacked.
# Deriving it also puts every published collision for MD5 out of reach as
# a copy, since all of them start from the standard IV behind a prefix their
# own author chose.
PREFIX_SEED = "cairn hash-differential v1 md5"
PREFIX = bytes.fromhex(
    "21013306c42165d036f7abcf74aa8a9214eb5b435ef908e07b5f374a4a71bdfb"
    "b58af043472653a3042b73e32842892c40a5ab63960a6a015617e5d7a158a395"
)
# Compression steps actually run.
# All of them -- the unmodified function.
STEPS = 64
# Leading digest bytes that must agree.
# All of them.
DIGEST_BYTES = 16
# The artifact is attacker-supplied and it is billing this node's CPU. A
# collision needs two blocks past the prefix, not sixty-four; the cap is
# generous and still bounds the check at a few thousand step functions.
MAX_MESSAGE_BYTES = 4096
_CLAIM = "collision on all 128 digest bits"
_ENDIAN = "little"

_M32 = 0xFFFFFFFF


def _rotl(x, n):
    x &= _M32
    return ((x << n) | (x >> (32 - n))) & _M32


def _pad(message):
    """Merkle-Damgard padding, little-endian length. RFC 1320 / RFC 1321."""
    bits = (8 * len(message)) & ((1 << 64) - 1)
    padded = message + b"\x80"
    padded += b"\x00" * ((56 - len(padded) % 64) % 64)
    return padded + bits.to_bytes(8, "little")


_MD5_IV = (0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476)
# floor(2^32 * abs(sin(i + 1))), the RFC 1321 table. Written out rather than
# computed from `math.sin`: this file decides who is paid, and a table derived
# through the platform's libm is a table that can differ between two honest
# nodes. Integers in the source cannot.
_MD5_K = (
    0xD76AA478, 0xE8C7B756, 0x242070DB, 0xC1BDCEEE,
    0xF57C0FAF, 0x4787C62A, 0xA8304613, 0xFD469501,
    0x698098D8, 0x8B44F7AF, 0xFFFF5BB1, 0x895CD7BE,
    0x6B901122, 0xFD987193, 0xA679438E, 0x49B40821,
    0xF61E2562, 0xC040B340, 0x265E5A51, 0xE9B6C7AA,
    0xD62F105D, 0x02441453, 0xD8A1E681, 0xE7D3FBC8,
    0x21E1CDE6, 0xC33707D6, 0xF4D50D87, 0x455A14ED,
    0xA9E3E905, 0xFCEFA3F8, 0x676F02D9, 0x8D2A4C8A,
    0xFFFA3942, 0x8771F681, 0x6D9D6122, 0xFDE5380C,
    0xA4BEEA44, 0x4BDECFA9, 0xF6BB4B60, 0xBEBFBC70,
    0x289B7EC6, 0xEAA127FA, 0xD4EF3085, 0x04881D05,
    0xD9D4D039, 0xE6DB99E5, 0x1FA27CF8, 0xC4AC5665,
    0xF4292244, 0x432AFF97, 0xAB9423A7, 0xFC93A039,
    0x655B59C3, 0x8F0CCC92, 0xFFEFF47D, 0x85845DD1,
    0x6FA87E4F, 0xFE2CE6E0, 0xA3014314, 0x4E0811A1,
    0xF7537E82, 0xBD3AF235, 0x2AD7D2BB, 0xEB86D391,
)
_MD5_S = (
    (7, 12, 17, 22), (5, 9, 14, 20), (4, 11, 16, 23), (6, 10, 15, 21),
)


def _compress(state, block):
    w = [int.from_bytes(block[4 * i:4 * i + 4], "little") for i in range(16)]
    a, b, c, d = state
    for i in range(STEPS):
        rnd = i // 16
        if rnd == 0:
            f, k = (b & c) | (~b & d), i
        elif rnd == 1:
            f, k = (d & b) | (~d & c), (5 * i + 1) % 16
        elif rnd == 2:
            f, k = b ^ c ^ d, (3 * i + 5) % 16
        else:
            f, k = c ^ (b | (~d & _M32)), (7 * i) % 16
        t = (a + (f & _M32) + _MD5_K[i] + w[k]) & _M32
        a, d, c, b = d, c, b, (b + _rotl(t, _MD5_S[rnd][i % 4])) & _M32
    return tuple((x + y) & _M32 for x, y in zip(state, (a, b, c, d)))


_IV = _MD5_IV


def _trace(message):
    """Chaining value after every block. The path is recomputed from here."""
    data = _pad(message)
    state = _IV
    chain = [state]
    for offset in range(0, len(data), 64):
        state = _compress(state, data[offset:offset + 64])
        chain.append(state)
    return chain


def _digest(chain):
    return b"".join(x.to_bytes(4, _ENDIAN) for x in chain[-1])


def _decode(value, field):
    if not isinstance(value, str) or not value:
        return None, "artifact.%s must be a non-empty lowercase hex string" % field
    # Length before content. The artifact is attacker-supplied and it is billing
    # this node's CPU, so the megabyte of hex that would be rejected anyway is
    # rejected before it is scanned and decoded rather than after.
    if len(value) > 2 * MAX_MESSAGE_BYTES:
        return None, (
            "artifact.%s may be at most %d hex characters; got %d"
            % (field, 2 * MAX_MESSAGE_BYTES, len(value))
        )
    if len(value) % 2:
        return None, "artifact.%s must have an even number of hex characters" % field
    if any(c not in "0123456789abcdef" for c in value):
        return None, "artifact.%s must be lowercase hex" % field
    return bytes.fromhex(value), None


def _path(left, right, chain_left, chain_right):
    """Describe the differential path the pair actually follows.

    Derived by recomputation, never read off a field the submitter filled in.
    An artifact carrying a path it does not follow is not a different verdict
    here, it is the same verdict with a different sentence attached -- which is
    the point: the pair is the claim, and the path is what the pair does.
    """
    words = [
        i for i in range(0, min(len(left), len(right)), 4)
        if left[i:i + 4] != right[i:i + 4]
    ]
    steps = [
        i for i, (x, y) in enumerate(zip(chain_left, chain_right)) if x != y
    ]
    if not steps:
        return "no block ever differs (%d message words differ)" % len(words)
    # Whether the pair is a true collision or only agrees on the compared
    # prefix is visible right here, in the last chaining value, so say which
    # rather than letting a truncated instance read as a full one.
    closed = chain_left[-1] == chain_right[-1]
    return (
        "%d message words differ, first at word %d; the chaining difference is "
        "nonzero after blocks %d..%d of %d, and %s"
        % (
            len(words), words[0] // 4, steps[0], steps[-1], len(chain_left) - 1,
            "zero from there on -- a collision in the full state"
            if closed else
            "still nonzero at the end, so the pair agrees on the compared "
            "digest prefix and not on the whole state",
        )
    )


def check(artifact):
    if not isinstance(artifact, dict):
        return False, "artifact must be an object"
    left, error = _decode(artifact.get("m"), "m")
    if error is not None:
        return False, error
    right, error = _decode(artifact.get("m_prime"), "m_prime")
    if error is not None:
        return False, error
    if left == right:
        return False, "m and m_prime are the same message; a hash collides with itself"
    if len(left) != len(right):
        return False, (
            "m and m_prime must have the same length; got %d and %d bytes"
            % (len(left), len(right))
        )
    if len(left) > MAX_MESSAGE_BYTES:
        return False, (
            "messages may be at most %d bytes; got %d"
            % (MAX_MESSAGE_BYTES, len(left))
        )
    if not left.startswith(PREFIX) or not right.startswith(PREFIX):
        return False, (
            "both messages must begin with the pinned %d-byte prefix"
            % len(PREFIX)
        )
    chain_left, chain_right = _trace(left), _trace(right)
    digest_left = _digest(chain_left)[:DIGEST_BYTES]
    digest_right = _digest(chain_right)[:DIGEST_BYTES]
    if digest_left != digest_right:
        differing = sum(
            bin(x ^ y).count("1") for x, y in zip(digest_left, digest_right)
        )
        return False, (
            "digests differ in %d of %d bits: %s vs %s"
            % (differing, 8 * DIGEST_BYTES, digest_left.hex(), digest_right.hex())
        )
    return True, "%s on %s: %s" % (
        _CLAIM, digest_left.hex(), _path(left, right, chain_left, chain_right)
    )
