"""Certificate checker: a conforming pair for MD4.

Full MD4, all 48 steps, all 128 digest bits, from a chaining value nobody
chose.

MD4 has been broken since Wang et al. (2005) and the attack has since been
sharpened to a couple of MD4 computations, so this is the cheapest real
differential-path work on the ladder -- an afternoon for someone implementing
the published path, and minutes for someone who already has. It is a bounty
rather than a demonstration only because *this* chaining value has not been
collided: the attack is public, the answer is not.

Nothing here helps you build the path, and the checker is indifferent to how
you built it.

# What is checked, exactly

Two hex messages of equal length, both beginning with the pinned prefix,
differing somewhere, whose digests are equal on all 128 bits. Nothing else.

Equal length is a requirement rather than an accident. A same-length collision
composes: H(m || x) = H(m' || x) for every x, because Merkle-Damgard feeds the
same chaining value into the same remaining blocks. Colliding pairs of
different lengths do not compose, and the property that makes a collision worth
paying for is exactly the one that survives being appended to.

# What this does NOT decide

Anything about method. A pair from a hand-built differential path, from
published tooling, or from a birthday search verifies identically -- which is
the property that makes an unreliable contributor safe to accept, and the
reason this network buys artifacts rather than effort.

It also decides nothing about MD4 in general: it decides one pair
against one pinned chaining value.

Cost is a few hundred MD4 computations with the published differential path.

# Provenance

Generated by `tools/build_pinned.py`; `--check` re-renders it and diffs. The
sha256 of this file is inside the objective's id, so the instance below IS part
of the objective's identity: nobody can retarget a funded bounty at an easier
prefix, and an edit forks the objective rather than rescoring work already
done against it.

Self-contained on purpose. `docs/verification.md` rule 4: a checker that reads
an unpinned file passes today and fails tomorrow at the same hash.
"""

# -- the pinned instance ----------------------------------------------------
#
# PREFIX is sha512 of the seed string below: 64 bytes, which is exactly one
# message block for this function. Derived and not chosen -- a funder who picks
# a prefix can pick one whose chaining value they have already attacked.
# Deriving it also puts every published collision for MD4 out of reach as
# a copy, since all of them start from the standard IV behind a prefix their
# own author chose.
PREFIX_SEED = "cairn hash-differential v1 md4"
PREFIX = bytes.fromhex(
    "7928f8077e557ed37b346f9f5eaa7bd1412f83fc8565f6d1695d43c8174203a5"
    "0e079353d1d1cb85a9682a076791ab2300f11d368c65e76bb6987dde09ca389b"
)
# Compression steps actually run.
# All of them -- the unmodified function.
STEPS = 48
# Leading digest bytes that must agree.
# All of them.
DIGEST_BYTES = 16
# The artifact is attacker-supplied and it is billing this node's CPU. A
# collision needs two blocks past the prefix, not sixty-four; the cap is
# generous and still bounds the check at a few thousand step functions.
MAX_MESSAGE_BYTES = 4096
_CLAIM = "collision on all 128 digest bits"
_ENDIAN = "little"

_M32 = 0xFFFFFFFF


def _rotl(x, n):
    x &= _M32
    return ((x << n) | (x >> (32 - n))) & _M32


def _pad(message):
    """Merkle-Damgard padding, little-endian length. RFC 1320 / RFC 1321."""
    bits = (8 * len(message)) & ((1 << 64) - 1)
    padded = message + b"\x80"
    padded += b"\x00" * ((56 - len(padded) % 64) % 64)
    return padded + bits.to_bytes(8, "little")


_MD4_IV = (0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476)
_MD4_ORDER = (
    tuple(range(16)),
    (0, 4, 8, 12, 1, 5, 9, 13, 2, 6, 10, 14, 3, 7, 11, 15),
    (0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15),
)
_MD4_SHIFT = ((3, 7, 11, 19), (3, 5, 9, 13), (3, 9, 11, 15))
_MD4_ADD = (0, 0x5A827999, 0x6ED9EBA1)


def _compress(state, block):
    w = [int.from_bytes(block[4 * i:4 * i + 4], "little") for i in range(16)]
    a, b, c, d = state
    for i in range(STEPS):
        rnd = i // 16
        if rnd == 0:
            f = (b & c) | (~b & d)
        elif rnd == 1:
            f = (b & c) | (b & d) | (c & d)
        else:
            f = b ^ c ^ d
        t = (a + (f & _M32) + w[_MD4_ORDER[rnd][i % 16]] + _MD4_ADD[rnd]) & _M32
        a, d, c, b = d, c, b, _rotl(t, _MD4_SHIFT[rnd][i % 4])
    return tuple((x + y) & _M32 for x, y in zip(state, (a, b, c, d)))


_IV = _MD4_IV


def _trace(message):
    """Chaining value after every block. The path is recomputed from here."""
    data = _pad(message)
    state = _IV
    chain = [state]
    for offset in range(0, len(data), 64):
        state = _compress(state, data[offset:offset + 64])
        chain.append(state)
    return chain


def _digest(chain):
    return b"".join(x.to_bytes(4, _ENDIAN) for x in chain[-1])


def _decode(value, field):
    if not isinstance(value, str) or not value:
        return None, "artifact.%s must be a non-empty lowercase hex string" % field
    # Length before content. The artifact is attacker-supplied and it is billing
    # this node's CPU, so the megabyte of hex that would be rejected anyway is
    # rejected before it is scanned and decoded rather than after.
    if len(value) > 2 * MAX_MESSAGE_BYTES:
        return None, (
            "artifact.%s may be at most %d hex characters; got %d"
            % (field, 2 * MAX_MESSAGE_BYTES, len(value))
        )
    if len(value) % 2:
        return None, "artifact.%s must have an even number of hex characters" % field
    if any(c not in "0123456789abcdef" for c in value):
        return None, "artifact.%s must be lowercase hex" % field
    return bytes.fromhex(value), None


def _path(left, right, chain_left, chain_right):
    """Describe the differential path the pair actually follows.

    Derived by recomputation, never read off a field the submitter filled in.
    An artifact carrying a path it does not follow is not a different verdict
    here, it is the same verdict with a different sentence attached -- which is
    the point: the pair is the claim, and the path is what the pair does.
    """
    words = [
        i for i in range(0, min(len(left), len(right)), 4)
        if left[i:i + 4] != right[i:i + 4]
    ]
    steps = [
        i for i, (x, y) in enumerate(zip(chain_left, chain_right)) if x != y
    ]
    if not steps:
        return "no block ever differs (%d message words differ)" % len(words)
    # Whether the pair is a true collision or only agrees on the compared
    # prefix is visible right here, in the last chaining value, so say which
    # rather than letting a truncated instance read as a full one.
    closed = chain_left[-1] == chain_right[-1]
    return (
        "%d message words differ, first at word %d; the chaining difference is "
        "nonzero after blocks %d..%d of %d, and %s"
        % (
            len(words), words[0] // 4, steps[0], steps[-1], len(chain_left) - 1,
            "zero from there on -- a collision in the full state"
            if closed else
            "still nonzero at the end, so the pair agrees on the compared "
            "digest prefix and not on the whole state",
        )
    )


def check(artifact):
    if not isinstance(artifact, dict):
        return False, "artifact must be an object"
    left, error = _decode(artifact.get("m"), "m")
    if error is not None:
        return False, error
    right, error = _decode(artifact.get("m_prime"), "m_prime")
    if error is not None:
        return False, error
    if left == right:
        return False, "m and m_prime are the same message; a hash collides with itself"
    if len(left) != len(right):
        return False, (
            "m and m_prime must have the same length; got %d and %d bytes"
            % (len(left), len(right))
        )
    if len(left) > MAX_MESSAGE_BYTES:
        return False, (
            "messages may be at most %d bytes; got %d"
            % (MAX_MESSAGE_BYTES, len(left))
        )
    if not left.startswith(PREFIX) or not right.startswith(PREFIX):
        return False, (
            "both messages must begin with the pinned %d-byte prefix"
            % len(PREFIX)
        )
    chain_left, chain_right = _trace(left), _trace(right)
    digest_left = _digest(chain_left)[:DIGEST_BYTES]
    digest_right = _digest(chain_right)[:DIGEST_BYTES]
    if digest_left != digest_right:
        differing = sum(
            bin(x ^ y).count("1") for x, y in zip(digest_left, digest_right)
        )
        return False, (
            "digests differ in %d of %d bits: %s vs %s"
            % (differing, 8 * DIGEST_BYTES, digest_left.hex(), digest_right.hex())
        )
    return True, "%s on %s: %s" % (
        _CLAIM, digest_left.hex(), _path(left, right, chain_left, chain_right)
    )
