"""Certificate checker: First-Blood ECDLP instance, 88-bit.

Recover k with k*G == Q on the curve below. Finding k is believed to cost
~sqrt(n) group operations; checking a claimed k is one scalar multiplication.
How it was found is irrelevant and unverifiable, which is the point.

**Nobody knows k, and that is checkable rather than promised.** Q is not a
multiple of G that somebody computed and discarded -- it is *hashed to the
curve* from the public seed below:

    x = sha256(SEED || bits || counter) mod p,  counter = 0, 1, 2, ...
    until x^3 + ax + b is a square; y = its canonical root

Q is therefore never built as k*G, so recovering log_G(Q) IS the ECDLP this
bounty pays for -- the funder has no more idea what k is than you do. Re-derive
it yourself: `_derive_q()` below runs at every check, and this file is pinned by
hash inside the objective's id.

Grinding the seed gains an attacker nothing. Profiting from a different seed
would mean recognising a Q whose logarithm you already know, and recognising one
means solving the instance.

What this does NOT prove: the curve (p, a, b, G) is still the poster's choice.
`check` verifies that N is prime-ish, and that G and Q both have order N, which
rules out a smooth-order curve; it does not rule out every weak-curve family.
Deriving the curve from the seed too is the stronger construction and is not
done here. See examples/first-blood/README.md.

The instance is derived, not baked in, and this file is pinned by hash inside
the objective's id, so the instance IS part of the objective's identity. Nobody
can retarget a funded bounty at an easier point.

Self-contained on purpose. The verifier pins the sha256 of THIS FILE ONLY -- an
imported helper module would not be covered by that hash, so shared curve
arithmetic would be an unpinned hole. Duplication is the price of pinning.

Generated by scripts/derive-first-blood.py. Do not edit by hand.
"""

import hashlib

P = 242741740111627334084264707
A = 134984510913594150542583735
B = 8920491190001754595878423
N = 242741740111604890660673023
GX = 141335002058520870978941080
GY = 113968915092050568385100851
BITS = 88
SEED = b'proofwork/first-blood/ecdlp/public-coin/v1'


def _on_curve(x, y):
    return (y * y - x * x * x - A * x - B) % P == 0


def _add(p, q):
    if p is None:
        return q
    if q is None:
        return p
    (x1, y1), (x2, y2) = p, q
    if x1 == x2 and (y1 + y2) % P == 0:
        return None
    if p == q:
        lam = (3 * x1 * x1 + A) * pow(2 * y1, P - 2, P) % P
    else:
        lam = (y2 - y1) * pow((x2 - x1) % P, P - 2, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def _mul(k, point):
    result, addend = None, point
    while k:
        if k & 1:
            result = _add(result, addend)
        addend = _add(addend, addend)
        k >>= 1
    return result


def _derive_q():
    """Hash-to-curve, try-and-increment. The whole provenance of the instance.

    Deterministic: same seed, same Q, forever, for anyone who runs it.
    """
    for counter in range(100000):
        digest = hashlib.sha256(
            SEED + b"/" + str(BITS).encode() + b"/" + str(counter).encode()
        ).digest()
        x = int.from_bytes(digest, "big") % P
        rhs = (x * x * x + A * x + B) % P
        if pow(rhs, (P - 1) // 2, P) != 1:
            continue
        y = pow(rhs, (P + 1) // 4, P)
        if (y * y - rhs) % P != 0:
            continue
        return x, min(y, P - y)
    return None


def check(artifact: dict) -> tuple[bool, str]:
    k = artifact.get("k")
    if isinstance(k, bool) or not isinstance(k, int):
        return False, "artifact.k must be an integer"
    # k is a group element exponent: any representative in [1, n) is a valid
    # discrete log, and there is exactly one.
    if not 1 <= k < N:
        return False, f"k must lie in [1, n) with n = {N}"
    q = _derive_q()
    if q is None:
        return False, "instance derivation failed"
    # Guard the constants themselves. If either point were off-curve, or either
    # had an order smaller than N, the objective would be unsatisfiable or
    # cheap -- and a submitter should not spend compute discovering that.
    if not _on_curve(GX, GY) or not _on_curve(*q):
        return False, "instance constants are not on the curve"
    if _mul(N, (GX, GY)) is not None or _mul(N, q) is not None:
        return False, "instance points do not have order N"
    got = _mul(k, (GX, GY))
    if got is None:
        return False, "k*G is the point at infinity"
    if got != q:
        return False, "k*G does not equal Q"
    return True, f"verified: k*G == Q on the {BITS}-bit public-coin instance"
