"""Ed25519 verification, and that it agrees with the Rust implementation.

The reference verifies signatures with a hand-written ed25519 because it has
no dependencies. That is only safe if it reaches the *same* verdict as the
Rust side on every input -- a signature one accepts and the other refuses is
two implementations disagreeing about which claims are valid, which is the one
thing this project cannot afford.

Two layers of check, and both are needed:

* RFC 8032 vectors prove the arithmetic is right.
* `conformance/signatures.json`, generated by the Rust test
  `signature_vectors_match_the_committed_file`, proves the two agree on
  signatures one of them actually produced. Two implementations can both
  satisfy RFC 8032 and still diverge on the strictness rules, which is exactly
  where a split would hide.
"""
import json
import pathlib

import pytest

from proofwork.ed25519 import L, is_usable_public_key, verify

# RFC 8032 section 7.1.
RFC_VECTORS = [
    (
        "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
        "",
        "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555f"
        "b8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
    ),
    (
        "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
        "72",
        "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da08"
        "5ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00",
    ),
    (
        "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
        "af82",
        "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac18"
        "ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a",
    ),
]

REPO = pathlib.Path(__file__).resolve().parents[3]
SIGNATURE_VECTORS = REPO / "conformance" / "signatures.json"


@pytest.mark.parametrize("public_key,message,signature", RFC_VECTORS)
def test_rfc8032_vectors_verify(public_key, message, signature):
    assert verify(
        bytes.fromhex(public_key), bytes.fromhex(message), bytes.fromhex(signature)
    )


def test_a_tampered_message_does_not_verify():
    public_key, message, signature = RFC_VECTORS[1]
    assert not verify(bytes.fromhex(public_key), b"\x73", bytes.fromhex(signature))


def test_small_order_public_keys_are_refused():
    # A small-order key verifies signatures anyone can produce, so accepting
    # one authenticates nothing -- an authentication bypass wearing a valid
    # signature. Rust's verify_bytes rejects these as key errors; so must this.
    _, _, signature = RFC_VECTORS[0]
    for weak in [bytes(32), bytes([1]) + bytes(31)]:
        assert not is_usable_public_key(weak)
        assert not verify(weak, b"", bytes.fromhex(signature))


def test_an_all_zero_signature_is_refused():
    # The Rust signer emits this when signing is impossible, precisely so it
    # fails loudly rather than passing for a real signature. Its R is
    # small-order.
    public_key, _, _ = RFC_VECTORS[0]
    assert not verify(bytes.fromhex(public_key), b"", bytes(64))


def test_a_non_canonical_scalar_is_refused():
    # S and S+L would otherwise be two encodings of one signature -- and
    # therefore two records with different ids, one of which was never signed.
    public_key, message, signature = RFC_VECTORS[1]
    raw = bytes.fromhex(signature)
    s = int.from_bytes(raw[32:], "little")
    malleable = raw[:32] + ((s + L) % (2**256)).to_bytes(32, "little")
    assert verify(bytes.fromhex(public_key), bytes.fromhex(message), raw)
    assert not verify(bytes.fromhex(public_key), bytes.fromhex(message), malleable)


def test_a_non_canonical_point_encoding_is_refused():
    # y >= p must not be reduced: reduction would let two distinct 32-byte
    # strings name one key, so a signature would verify under a public key
    # nobody ever published.
    non_canonical = (2**255 - 19).to_bytes(32, "little")
    assert not is_usable_public_key(non_canonical)


def test_malformed_lengths_are_refused_rather_than_raising():
    # These arrive from records other people wrote. A verifier that raises on
    # a short field is a node that crashes on a hostile log.
    assert not verify(b"", b"m", bytes(64))
    assert not verify(bytes(32), b"m", b"")
    assert not verify(bytes(31), b"m", bytes(64))


def test_signatures_the_rust_implementation_produced_verify_here():
    # The assertion that actually establishes cross-implementation agreement.
    # Regenerate with:
    #   PROOFWORK_WRITE_VECTORS=1 cargo test --test crypto signature_vectors
    assert SIGNATURE_VECTORS.exists(), f"{SIGNATURE_VECTORS} is missing"
    vectors = json.loads(SIGNATURE_VECTORS.read_text())
    assert vectors, "the vector file is empty"
    for vector in vectors:
        public_key = bytes.fromhex(vector["public_key"])
        message = bytes.fromhex(vector["message_hex"])
        signature = bytes.fromhex(vector["signature"])
        assert verify(public_key, message, signature), vector["public_key"]
        # A one-bit change anywhere in the record must break it, or the
        # signature is not binding the record.
        tampered = bytearray(message)
        tampered[-1] ^= 1
        assert not verify(public_key, bytes(tampered), signature)
