"""Evaluator: how light can a SHA-0 disturbance vector be?

SHA-0's expansion, W[i] = W[i-3] ^ W[i-8] ^ W[i-14] ^ W[i-16], has no
rotation in it. XOR acts on each of the 32 bit positions separately, so a
codeword of this recurrence is 32 independent codewords of one length-80 binary
code with 16 free bits -- and the weight of the whole is the sum of the weights
of the parts.

**That makes this objective exhaustively solvable, and its optimum proved.**
The lightest vector overall is the lightest vector in one bit position, because
using a second position only adds weight; and one bit position has 2^16
codewords, which is a loop. `tools/search_dv.py` runs it. The answer is 17, the
pool is exactly exhausted there, and `artifacts/dv-sha0-optimal.json` reaches
it.

It is here as the control for `dv_sha1.py`, which is the same objective over
the same recurrence with the rotation put back, and which nobody can solve this
way. Two files, one line of difference, and the whole reason SHA-1 replaced
SHA-0 sits in the gap between what the two can prove.

# What a disturbance vector is, and what this scores

A collision attack on a SHA-family compression function is built by picking a
difference in the expanded message words that can be cancelled, step by step,
by local collisions -- a disturbance at step i, and corrections at steps
i+1..i+5 that undo it. The difference has to be a codeword of the message
expansion, because expanded words are not free: they are determined by the
first sixteen. That codeword is the disturbance vector, and it is chosen before
any of the rest of the attack exists.

Its weight is what the attack costs. Every disturbed bit forces roughly two
conditions on the working state, and conditions in steps a message-modification
pass cannot reach have to be met by search. So:

    score = sum of the Hamming weights of DV[20..79], minimised

**This is a proxy and it is stated as one.** True attack cost also depends on
which bit positions are disturbed, on how local collisions overlap, and on how
far message modification actually reaches. What is being bought here is a
low-weight codeword of a specific linear code over a specific range, decided
exactly, and not a claim about anybody's attack.

# Why an empty answer cannot take the pool

The all-zero vector is a codeword, weighs nothing, and describes no attack, so
on a minimise objective it would take the frontier and the pool behind it.
Two things stop it. It is refused outright. And it could not have won anyway:
the score range is 60 words wide and the tail is required to be zero, so a
vector scoring 0 would have 60 consecutive zero words -- and any 16 consecutive
words determine a codeword everywhere, so 16 zeros already force the all-zero
vector. The minimum achievable score is bounded away from zero by the geometry
of the code, not by the guard, which is the version of that argument worth
having.

# Provenance

Generated by `tools/build_pinned.py`; `--check` re-renders it and diffs. The
sha256 of this file is inside the objective's id, so an edit forks the
objective rather than rescoring work already done against it.

Returns an int. Never a float -- see `src/verifiers/mod.rs` for why.
"""

# The one line that separates this file from dv_sha1.py.
ROTATE_EXPANSION = False

STEPS = 80
# Steps 0..19 are free to an attacker: the first sixteen message words are
# chosen directly, so conditions there are met by construction rather than by
# search. The weight that costs anything is what is left after that, which is
# why the score starts at step 20 and not at step 0.
SCORE_FROM = 20
# A disturbance at step i is cancelled by corrections at steps i+1..i+5. There
# is no step 80, so a disturbance at 75 or later has no room to be corrected
# and the vector cannot be completed into local collisions inside one
# compression. Refused rather than scored: a vector that cannot be used is not
# a good vector that happens to be cheap.
#
# Multi-block attacks relax exactly this, letting the uncorrected tail become a
# near-collision that the next block cancels. A vector refused here can still
# be useful there -- this objective buys single-block vectors, and says so.
TAIL_FROM = 75
MAX_OFFSET = STEPS - 16

# What an invalid artifact scores.
#
# A *minimise* objective cannot reject with zero, because zero is the best
# score expressible: the all-zero vector satisfies the recurrence, weighs
# nothing, and would take the frontier and the whole pool behind it while
# describing no attack at all. The rejection value has to be worse than every
# honest answer, which on this direction means larger than the heaviest
# possible vector.
INVALID = 32 * (STEPS - SCORE_FROM) + 1

_M32 = 0xFFFFFFFF


def _rotl(x, n):
    return ((x << n) | (x >> (32 - n))) & _M32


def _expand(window, offset):
    """The 80-word codeword through the real message expansion, both ways.

    Sixteen consecutive words determine a codeword everywhere, because the
    recurrence is invertible: forwards it is the expansion itself, and
    backwards W[i] = R'(W[i+16]) ^ W[i+13] ^ W[i+8] ^ W[i+2]. Accepting a
    window at any offset is not a convenience -- published vectors are named by
    the position of the window that generates them, and forcing them to be
    re-anchored at step 0 by hand would make transcription errors the most
    likely failure of a submission.
    """
    dv = [0] * STEPS
    dv[offset:offset + 16] = window
    for i in range(offset + 16, STEPS):
        x = dv[i - 3] ^ dv[i - 8] ^ dv[i - 14] ^ dv[i - 16]
        dv[i] = _rotl(x, 1) if ROTATE_EXPANSION else x
    for i in range(offset - 1, -1, -1):
        x = _rotl(dv[i + 16], 31) if ROTATE_EXPANSION else dv[i + 16]
        dv[i] = x ^ dv[i + 13] ^ dv[i + 8] ^ dv[i + 2]
    return dv


def _window(artifact):
    """The 16 seed words, or None. Shape errors are scores, never exceptions."""
    if not isinstance(artifact, dict):
        return None
    offset = artifact.get("offset")
    if not isinstance(offset, int) or isinstance(offset, bool):
        return None
    if not 0 <= offset <= MAX_OFFSET:
        return None
    words = artifact.get("window")
    if not isinstance(words, list) or len(words) != 16:
        return None
    decoded = []
    for word in words:
        # Exactly one spelling, so one vector has one artifact and one digest.
        # "0x1", "1" and "00000001" are the same number and would otherwise be
        # three settling answers to one problem.
        if not isinstance(word, str) or len(word) != 8:
            return None
        if any(c not in "0123456789abcdef" for c in word):
            return None
        decoded.append(int(word, 16))
    return offset, decoded


def score(artifact):
    parsed = _window(artifact)
    if parsed is None:
        return INVALID
    offset, window = parsed
    dv = _expand(window, offset)
    if not any(dv):
        return INVALID
    if any(dv[i] for i in range(TAIL_FROM, STEPS)):
        return INVALID
    return sum(bin(dv[i]).count("1") for i in range(SCORE_FROM, STEPS))
