//! A verifiable delay function, and the beacon that stops a sequencer grinding.
//!
//! # The attack this closes
//!
//! Settlement orders each epoch's batch by a beacon, and the frontier's
//! work assignment is drawn from one. Before this, the beacon fell back to the
//! epoch-chain head — a value the sequencer computes and therefore *chooses*,
//! by deciding what to append and in which order. Trying a hundred orderings
//! and keeping the one that pays your own claim first is grinding, it costs a
//! hundred hashes, and since epoch-batched settlement started ordering payouts
//! by that value it moves money rather than only work.
//!
//! A verifiable delay function makes the beacon **slow to compute and fast to
//! check**. The sequencer cannot try a hundred candidates because each one costs
//! the full delay, and it cannot try them in parallel because the computation is
//! inherently sequential — that is the whole content of the primitive.
//!
//! # Wesolowski, over an RSA group
//!
//! ```text
//! y = x^(2^T) mod N
//! l = the prime Fiat–Shamir draws from (x, y, T)
//! π = x^⌊2^T / l⌋ mod N
//! check: π^l · x^(2^T mod l) == y
//! ```
//!
//! Proving costs `T` squarings and cannot be parallelised: squaring `2^T` times
//! is `T` steps each of which needs the last one's answer. Verifying costs two
//! exponentiations by ~128-bit numbers, which is microseconds. That asymmetry is
//! the point.
//!
//! **The group must have unknown order.** If anyone knows `φ(N)` they can
//! shortcut `2^T` to `2^T mod φ(N)` and produce the answer instantly, which
//! makes the delay imaginary. So `N` is [`RSA_2048`] — the RSA Factoring
//! Challenge modulus, whose factors have never been published and whose
//! generation was witnessed. Choosing a modulus *this* implementation generated
//! would mean whoever ran the generator can grind freely, which is the attack
//! wearing a hat.
//!
//! # What this does not do
//!
//! It bounds *grinding*, not *withholding*. A sequencer that does not like the
//! beacon it computed can still decline to publish one, and the epoch then
//! settles under the documented fallback with `epochs_without_beacon` naming it.
//! Refusing to settle instead would strand every claim in the epoch, which
//! hands a censor a better weapon than the one being taken away. See
//! `CAIRN_REQUIRE_BEACON` for the reader-side policy that makes the absence
//! refusable rather than invisible.

use sha2::{Digest, Sha256};

use crate::crypto::bignum::{Montgomery, Nat};

/// Raw SHA-256, because everything here is arithmetic on bytes rather than on
/// record identifiers. `canonical::digest_bytes` returns the `sha256:`-prefixed
/// hex a record carries, which is the wrong shape for hashing into a group.
fn sha256(data: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(data);
    let out = hasher.finalize();
    let mut bytes = [0u8; 32];
    bytes.copy_from_slice(&out);
    bytes
}

/// The RSA Factoring Challenge's 2048-bit modulus.
///
/// A **nothing-up-my-sleeve** parameter, and the reason it is a constant rather
/// than a setting. A VDF over a modulus somebody knows the factorisation of is
/// not a delay function at all — the holder of `φ(N)` reduces the exponent and
/// answers instantly — so the modulus has to be one where *nobody* plausibly
/// holds that secret. RSA-2048 was generated in a witnessed ceremony, its
/// factors were never published, the prize for factoring it went unclaimed, and
/// it is the same choice Chia and the Ethereum VDF research used.
///
/// A modulus generated by this crate would be strictly worse: whoever ran the
/// generator could grind at will and no reader could tell.
pub const RSA_2048: &str = "\
c7970ceedcc3b0754490201a7aa613cd73911081c790f5f1a8726f463550bb5b7ff0db8e1ea1189e\
c72f93d1650011bd721aeeacc2acde32a04107f0648c2813a31f5b0b7765ff8b44b4b6ffc93384b6\
46eb09c7cf5e8592d40ea33c80039f35b4f14a04b51f7bfd781be4d1673164ba8eb991c2c4d730bb\
be35f592bdef524af7e8daefd26c66fc02c479af89d64d373f442709439de66ceb955f3ea37d5159\
f6135809f85334b5cb1813addc80cd05609f10ac6a95ad65872c909525bdad32bc729592642920f2\
4c61dc5b3c3b7923e56b16a4d9d373d8721f24a3fc0f1b3131f55615172866bccc30f95054c824e7\
33a5eb6817f7bc16399d48c6361cc7e5";

/// How many bytes the group's elements serialise to.
pub const ELEMENT_BYTES: usize = 256;

/// Bits of the Fiat–Shamir challenge prime.
///
/// 128 is the standard choice and it is a soundness parameter, not a size one:
/// a cheating prover wins by finding a proof that happens to satisfy the check
/// for the `l` it will be handed, and the chance of that is about `1/l`.
const CHALLENGE_BITS: usize = 128;

/// A computed delay, and the proof that it was computed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Proof {
    /// `x^(2^T) mod N`, big-endian, [`ELEMENT_BYTES`] wide.
    pub output: Vec<u8>,
    /// `x^⌊2^T/l⌋ mod N`, same encoding.
    pub witness: Vec<u8>,
}

impl Proof {
    pub fn output_hex(&self) -> String {
        crate::hex::encode(&self.output)
    }

    pub fn witness_hex(&self) -> String {
        crate::hex::encode(&self.witness)
    }
}

/// The group element a seed maps to.
///
/// Hashed rather than taken directly, so a caller cannot choose `x` — an
/// attacker who picked `x = 1` would have a VDF whose answer is 1 at every
/// difficulty. Hashing twice and concatenating widens the digest to a
/// respectable fraction of the modulus without needing a full hash-to-group
/// construction; the security argument only needs `x` to be a value nobody
/// chose, and the group is large enough that a 512-bit uniform value is not a
/// weak input.
pub fn element(seed: &[u8]) -> Nat {
    let mut bytes = Vec::with_capacity(64);
    bytes.extend_from_slice(&sha256(&[b"proofwork/vdf/x1".as_slice(), seed].concat()));
    bytes.extend_from_slice(&sha256(&[b"proofwork/vdf/x2".as_slice(), seed].concat()));
    let modulus = modulus();
    Nat::from_be_bytes(&bytes).rem(&modulus)
}

/// [`RSA_2048`] as a number.
pub fn modulus() -> Nat {
    let bytes: Vec<u8> = (0..RSA_2048.len())
        .step_by(2)
        .map(|index| {
            u8::from_str_radix(&RSA_2048[index..index + 2], 16)
                .expect("the modulus constant is hex")
        })
        .collect();
    Nat::from_be_bytes(&bytes)
}

/// The Fiat–Shamir challenge: the first prime at or above the digest of the
/// transcript.
///
/// The transcript is `(x, y, T)` and all three have to be in it. Leaving `T`
/// out would let a prover compute an honest proof at a *smaller* difficulty and
/// present it for a larger one, which is the entire delay evaporating; leaving
/// `y` out would let the challenge be known before the work was done, and a
/// prover who knows `l` in advance can construct `y` and `π` that satisfy the
/// check without ever squaring.
pub fn challenge(x: &Nat, y: &Nat, difficulty: u64) -> Nat {
    let mut transcript = Vec::new();
    transcript.extend_from_slice(b"proofwork/vdf/challenge");
    transcript.extend_from_slice(&x.to_be_bytes(ELEMENT_BYTES));
    transcript.extend_from_slice(&y.to_be_bytes(ELEMENT_BYTES));
    transcript.extend_from_slice(&difficulty.to_be_bytes());
    let digest = sha256(&transcript);
    // Take the top `CHALLENGE_BITS`, force it odd and above 2, then walk up to
    // the next probable prime. Deterministic, so every node draws the same `l`
    // from the same transcript -- which it must, or verification is a coin flip.
    let mut top = digest[..CHALLENGE_BITS / 8].to_vec();
    // Clear the high bit so `l` stays below 2^127 even after walking up to the
    // next prime. The streaming quotient in `prove` keeps `2r + 1` in a `u128`,
    // and a challenge that crept over 2^128 through a prime gap would overflow
    // it silently -- a beacon that verifies on one machine and not another.
    top[0] &= 0x7f;
    let mut candidate = Nat::from_be_bytes(&top);
    if !candidate.is_odd() {
        candidate = candidate.add(&Nat::one());
    }
    while !is_probable_prime(&candidate) {
        candidate = candidate.add(&Nat::from_u64(2));
    }
    candidate
}

/// Miller–Rabin with fixed bases.
///
/// Fixed rather than random, because this runs inside a consensus rule: two
/// nodes that drew different bases could disagree about whether a challenge is
/// prime, and then about whether a beacon verifies. The bases are the first
/// twelve primes, which is a deterministic test for everything below 3.3 × 10^24
/// and an overwhelming probabilistic one above it.
fn is_probable_prime(n: &Nat) -> bool {
    const BASES: [u64; 12] = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37];
    if n.cmp(&Nat::from_u64(2)) == core::cmp::Ordering::Less {
        return false;
    }
    for base in BASES {
        let base = Nat::from_u64(base);
        if n.cmp(&base) == core::cmp::Ordering::Equal {
            return true;
        }
        if n.rem(&base).is_zero() {
            return false;
        }
    }
    let Some(m) = Montgomery::new(n.clone()) else {
        return false;
    };
    let one = Nat::one();
    let n_minus_one = n.sub(&one);
    // n - 1 = d * 2^s with d odd.
    let mut s = 0usize;
    while !n_minus_one.bit(s) {
        s += 1;
    }
    let d = shift_right(&n_minus_one, s);

    'base: for base in BASES {
        let mut x = m.pow(&Nat::from_u64(base), &d);
        if x.cmp(&one) == core::cmp::Ordering::Equal
            || x.cmp(&n_minus_one) == core::cmp::Ordering::Equal
        {
            continue;
        }
        for _ in 1..s {
            x = m.leave(&m.mul(&m.enter(&x), &m.enter(&x)));
            if x.cmp(&n_minus_one) == core::cmp::Ordering::Equal {
                continue 'base;
            }
        }
        return false;
    }
    true
}

fn shift_right(value: &Nat, bits: usize) -> Nat {
    let mut out = Nat::zero();
    let total = value.bits();
    for index in (bits..total).rev() {
        out = out.shl(1);
        if value.bit(index) {
            out = out.add(&Nat::one());
        }
    }
    out
}

/// Compute the delay and its proof.
///
/// `difficulty` is the number of sequential squarings, and it is the parameter
/// the whole construction rests on: too small and the sequencer can afford to
/// grind anyway, too large and honest nodes cannot produce a beacon inside the
/// epoch that needs it. It belongs in the record so a verifier reads it rather
/// than assuming it.
pub fn prove(seed: &[u8], difficulty: u64) -> Proof {
    let m = Montgomery::new(modulus()).expect("the modulus is odd");
    let x = element(seed);

    // The sequential part. Nothing here can be parallelised or skipped without
    // knowing the group's order, which is the security assumption.
    let mut y = m.enter(&x);
    for _ in 0..difficulty {
        y = m.mul(&y, &y);
    }
    let y = m.leave(&y);

    let l = challenge(&x, &y, difficulty);
    // π = x^⌊2^T/l⌋, computed by streaming the long division rather than
    // materialising a `T`-bit quotient: at a difficulty of a million that
    // number is 125 kilobytes and every multiplication by it is quadratic.
    // The quotient is a `T`-bit number -- 125 kilobytes at a difficulty of a
    // million -- so it is never materialised. Each step emits one bit of it by
    // long division, and because `l` is under 2^127 the whole recurrence fits
    // in a `u128`: a bignum `divrem` per squaring made proving five times
    // slower than the squarings it was supposed to accompany.
    let small = l.to_u128().expect("the challenge is under 2^127");
    let mut witness = m.one();
    let entered = m.enter(&x);
    let mut remainder: u128 = 0;
    for _ in 0..difficulty {
        // value = 2 * remainder + 1, which needs 129 bits; the carry is
        // tracked rather than widened.
        let (doubled, carry) = remainder.overflowing_add(remainder);
        let (value, carry_two) = doubled.overflowing_add(1);
        let over = carry || carry_two;
        witness = m.mul(&witness, &witness);
        // `remainder < l` on entry, so `value < 2l` and one subtraction is
        // always enough.
        if over || value >= small {
            remainder = value.wrapping_sub(small);
            witness = m.mul(&witness, &entered);
        } else {
            remainder = value;
        }
    }
    Proof {
        output: y.to_be_bytes(ELEMENT_BYTES),
        witness: m.leave(&witness).to_be_bytes(ELEMENT_BYTES),
    }
}

/// Does this proof show that `seed` at `difficulty` really produces `output`?
///
/// Two exponentiations by numbers of about 128 bits, whatever the difficulty.
/// That is the asymmetry the whole design is for: a beacon that took a second
/// to produce is checked in microseconds, by everyone, forever.
pub fn verify(seed: &[u8], difficulty: u64, proof: &Proof) -> bool {
    if proof.output.len() != ELEMENT_BYTES || proof.witness.len() != ELEMENT_BYTES {
        return false;
    }
    let m = Montgomery::new(modulus()).expect("the modulus is odd");
    let x = element(seed);
    let y = Nat::from_be_bytes(&proof.output);
    let witness = Nat::from_be_bytes(&proof.witness);
    if y.cmp(m.modulus()) != core::cmp::Ordering::Less
        || witness.cmp(m.modulus()) != core::cmp::Ordering::Less
    {
        return false;
    }
    let l = challenge(&x, &y, difficulty);
    // r = 2^T mod l by modular exponentiation -- `log T` multiplications, not
    // `T`. Doubling `T` times here was the first version, and it made
    // verification cost the same order as proving, which is the one thing a
    // verifiable *delay* function must not do: the asymmetry is the primitive.
    let small = Montgomery::new(l.clone()).expect("the challenge is an odd prime");
    let r = small.pow(&Nat::from_u64(2), &Nat::from_u64(difficulty));
    let left = m.mul(&m.enter(&m.pow(&witness, &l)), &m.enter(&m.pow(&x, &r)));
    m.leave(&left).cmp(&y) == core::cmp::Ordering::Equal
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_proof_verifies_and_a_forged_one_does_not() {
        let seed = b"epoch 12345";
        let proof = prove(seed, 512);
        assert!(verify(seed, 512, &proof));

        // A different seed is a different beacon. This is the property that
        // stops a sequencer reusing one epoch's answer in another.
        assert!(!verify(b"epoch 12346", 512, &proof));

        // A different difficulty is a different beacon too, which is why `T`
        // is inside the Fiat-Shamir transcript: without it, a prover computes
        // an honest proof cheaply at T = 1 and presents it for T = 2^30.
        assert!(!verify(seed, 511, &proof));
        assert!(!verify(seed, 1024, &proof));
    }

    #[test]
    fn the_output_cannot_be_edited_without_the_proof_failing() {
        let seed = b"grind me";
        let mut proof = prove(seed, 256);
        assert!(verify(seed, 256, &proof));

        // Flipping one bit of the answer. A sequencer that wants a different
        // beacon has to redo the delay, which is the entire point.
        proof.output[ELEMENT_BYTES - 1] ^= 1;
        assert!(!verify(seed, 256, &proof));

        // And the witness is not free to choose either.
        let mut proof = prove(seed, 256);
        proof.witness[0] ^= 0x80;
        assert!(!verify(seed, 256, &proof));
    }

    #[test]
    fn an_element_out_of_range_is_refused_rather_than_reduced() {
        // A value at or above the modulus is not a group element. Reducing it
        // silently would give two encodings of one beacon, and a record whose
        // canonical form is not a function of its meaning.
        let seed = b"range";
        let proof = prove(seed, 64);
        let mut oversized = proof.clone();
        oversized.output = modulus().to_be_bytes(ELEMENT_BYTES);
        assert!(!verify(seed, 64, &oversized));

        // Wrong width is refused before any arithmetic.
        let mut short = proof.clone();
        short.output.truncate(ELEMENT_BYTES - 1);
        assert!(!verify(seed, 64, &short));
    }

    #[test]
    fn the_challenge_is_a_prime_every_node_draws_the_same_way() {
        let x = element(b"a");
        let y = element(b"b");
        let l = challenge(&x, &y, 1024);
        assert!(is_probable_prime(&l));
        assert_eq!(l, challenge(&x, &y, 1024));
        // All three transcript components move it.
        assert_ne!(l, challenge(&y, &x, 1024));
        assert_ne!(l, challenge(&x, &y, 1025));
    }

    #[test]
    fn miller_rabin_agrees_with_known_primes_and_composites() {
        for prime in [2u64, 3, 5, 7, 97, 65537, 2147483647, 1000000007] {
            assert!(is_probable_prime(&Nat::from_u64(prime)), "{prime}");
        }
        for composite in [0u64, 1, 4, 9, 25, 91, 561, 1105, 1729, 2465, 65536] {
            assert!(!is_probable_prime(&Nat::from_u64(composite)), "{composite}");
        }
        // 561, 1105, 1729, 2465 are Carmichael numbers -- the composites that
        // fool a naive Fermat test. Included because a Fermat test is the
        // mistake this function is one refactor away from becoming.
    }

    #[test]
    fn difficulty_zero_is_the_identity_and_still_verifies() {
        // Not a useful beacon, and it must not be a *wrong* one: the edge case
        // where the loop body never runs is where an off-by-one in the proof
        // stream would show up.
        let seed = b"zero";
        let proof = prove(seed, 0);
        assert!(verify(seed, 0, &proof));
        assert_eq!(
            Nat::from_be_bytes(&proof.output),
            element(seed),
            "x^(2^0) is x squared zero times, which is x"
        );
    }
    /// Verification cost must not grow with the difficulty.
    ///
    /// **This is the primitive.** A delay function whose verification costs the
    /// same order as its proving is just a slow function, and the first version
    /// of `verify` here was exactly that: it computed `2^T mod l` by doubling
    /// `T` times, so checking a beacon cost what producing it cost and every
    /// node in the network paid the delay. Measured at 302ms for T = 100,000,
    /// against 5ms once the exponentiation was done properly.
    ///
    /// Timed rather than counted, because the bug was algorithmic and a wall
    /// clock is what noticed it. The bound is deliberately loose, so this fails
    /// on a regression to linear cost and not on a slow machine.
    #[test]
    fn verifying_costs_the_same_at_any_difficulty() {
        use std::time::Instant;

        // A well-formed proof that does not check. Verification does the same
        // work either way, and this avoids spending minutes *proving* at a
        // difficulty chosen to make the point.
        let bogus = Proof {
            output: element(b"not the answer").to_be_bytes(ELEMENT_BYTES),
            witness: element(b"nor this").to_be_bytes(ELEMENT_BYTES),
        };
        assert!(!verify(b"seed", 1_000, &bogus));

        let start = Instant::now();
        assert!(!verify(b"seed", 1_000, &bogus));
        let small = start.elapsed();

        let start = Instant::now();
        assert!(!verify(b"seed", 1_000_000_000, &bogus));
        let huge = start.elapsed();

        // A millionfold more difficulty. Linear verification would be a
        // millionfold more time; constant verification is the same time.
        assert!(
            huge < small * 100 + std::time::Duration::from_millis(200),
            "verification scaled with difficulty: {small:?} at 10^3, {huge:?} at 10^9"
        );
    }
}
