//! `proofwork-reference` — the independent checker.
//!
//! Two jobs:
//!
//! * `conformance <vectors.json>` — reproduce every frozen vector. These were
//!   generated by the Python reference that this crate replaces, which is the
//!   point: they are the surviving evidence from an implementation written in
//!   another language, and they keep proving the format is a format rather
//!   than a description of one program's behaviour.
//! * `audit <log.jsonl>` — re-derive a log the primary implementation wrote:
//!   chain integrity, record ids, signatures, Merkle root.

use std::process::ExitCode;

use proofwork_reference::canonical::{merkle_root, Value};
use proofwork_reference::frontier::Ratchet;
use proofwork_reference::ledger::Ledger;
use proofwork_reference::partition::{assign, beacon, settlement_rank};
use proofwork_reference::records::{commitment_hash, Claim, Commitment, Objective};

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let result = match args.first().map(String::as_str) {
        Some("conformance") => conformance(args.get(1).map(String::as_str)),
        Some("audit") => audit(args.get(1).map(String::as_str)),
        Some("--help") | Some("help") | None => {
            eprintln!(
                "proofwork-reference — an independent check on the primary implementation\n\n\
                 USAGE\n    \
                 proofwork-reference conformance <conformance/vectors.json>\n    \
                 proofwork-reference audit <log.jsonl>\n"
            );
            return ExitCode::SUCCESS;
        }
        Some(other) => Err(format!("unknown command {other:?}")),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("proofwork-reference: {message}");
            ExitCode::FAILURE
        }
    }
}

fn read(path: Option<&str>, what: &str) -> Result<String, String> {
    let path = path.ok_or_else(|| format!("expected a path to {what}"))?;
    std::fs::read_to_string(path).map_err(|error| format!("cannot read {path}: {error}"))
}

/// Every failure is collected rather than returned at the first one: knowing
/// that four sections disagree tells you something different from knowing that
/// one does, and an implementer fixing a format bug wants the whole list.
struct Failures(Vec<String>);

impl Failures {
    fn check(
        &mut self,
        section: &str,
        label: &str,
        got: impl std::fmt::Debug,
        want: impl std::fmt::Debug,
    ) {
        let (got, want) = (format!("{got:?}"), format!("{want:?}"));
        if got != want {
            self.0.push(format!(
                "{section}: {label}\n    got  {got}\n    want {want}"
            ));
        }
    }
}

fn conformance(path: Option<&str>) -> Result<(), String> {
    let text = read(path, "conformance/vectors.json")?;
    let vectors = Value::from_json(&text).map_err(|e| e.to_string())?;
    let mut f = Failures(Vec::new());
    let mut checked = 0usize;

    // -- canonical encoding, the contract everything else rests on ----------
    for case in section(&vectors, "canonical")? {
        let value = case.get("value").ok_or("canonical case needs a value")?;
        let want_utf8 = str_of(case, "canonical_utf8")?;
        f.check(
            "canonical",
            want_utf8,
            value.canonical_string(),
            want_utf8.to_string(),
        );
        f.check(
            "canonical",
            &format!("digest of {want_utf8}"),
            value.digest(),
            str_of(case, "digest")?.to_string(),
        );
        // The decoder must round-trip its own encoder's output, or a log this
        // implementation wrote could not be read back by it.
        if let Ok(reparsed) = Value::from_json(&value.canonical_string()) {
            f.check(
                "canonical",
                &format!("round trip {want_utf8}"),
                reparsed,
                value.clone(),
            );
        } else {
            f.0.push(format!("canonical: {want_utf8} did not re-parse"));
        }
        checked += 1;
    }

    // -- merkle: the odd node is promoted, not duplicated -------------------
    for case in section(&vectors, "merkle")? {
        let leaves: Vec<String> = case
            .get("leaves")
            .and_then(Value::as_array)
            .ok_or("merkle case needs leaves")?
            .iter()
            .filter_map(|v| v.as_str().map(str::to_string))
            .collect();
        let want = case.get("root").and_then(Value::as_str).map(str::to_string);
        f.check(
            "merkle",
            &format!("{} leaves", leaves.len()),
            merkle_root(&leaves),
            want,
        );
        checked += 1;
    }

    // -- record identity ----------------------------------------------------
    let records = vectors
        .get("records")
        .ok_or("vectors need a records section")?;
    for case in array(records, "objectives")? {
        let record = case.get("record").ok_or("objective case needs a record")?;
        let objective = Objective::from_value(record).map_err(|e| format!("objective: {e}"))?;
        f.check(
            "records",
            "objective id",
            objective.id(),
            str_of(case, "id")?.to_string(),
        );
        // The canonical form must round-trip: decoding and re-encoding a
        // record has to reproduce it byte for byte, or an id moves when a
        // record is merely relayed.
        f.check(
            "records",
            "objective re-encode",
            objective.to_value(),
            record.clone(),
        );
        checked += 1;
    }
    for case in array(records, "commitments")? {
        let record = case.get("record").ok_or("commitment case needs a record")?;
        let commitment = Commitment::from_value(record).map_err(|e| format!("commitment: {e}"))?;
        f.check(
            "records",
            "commitment id",
            commitment.id(),
            str_of(case, "id")?.to_string(),
        );
        f.check(
            "records",
            "commitment re-encode",
            commitment.to_value(),
            record.clone(),
        );
        checked += 1;
    }
    for case in array(records, "claims")? {
        let record = case.get("record").ok_or("claim case needs a record")?;
        let claim = Claim::from_value(record).map_err(|e| format!("claim: {e}"))?;
        f.check(
            "records",
            "claim id",
            claim.id(),
            str_of(case, "id")?.to_string(),
        );
        f.check(
            "records",
            "claim re-encode",
            claim.to_value(),
            record.clone(),
        );
        f.check(
            "records",
            "claim artifact_id",
            claim.artifact_id(),
            str_of(case, "artifact_id")?.to_string(),
        );
        f.check(
            "records",
            "commitment_hash",
            commitment_hash(
                &claim.objective_id,
                &claim.submitter,
                &claim.artifact,
                &claim.nonce,
            ),
            str_of(case, "commitment_hash")?.to_string(),
        );
        checked += 1;
    }

    // -- the settlement beacon and work assignment --------------------------
    for case in section(&vectors, "partition")? {
        let anchor = str_of(case, "anchor")?;
        let epoch = case.get("epoch").and_then(Value::as_u64).unwrap_or(0);
        if let Some(want) = case.get("beacon").and_then(Value::as_str) {
            f.check(
                "partition",
                "beacon",
                beacon(epoch, anchor),
                want.to_string(),
            );
        }
        for assignment in case
            .get("assignments")
            .and_then(Value::as_array)
            .unwrap_or(&[])
        {
            let node_id = str_of(assignment, "node_id")?;
            let objective_id = str_of(assignment, "objective_id")?;
            let partitions = assignment
                .get("partitions")
                .and_then(Value::as_u64)
                .ok_or("assignment needs partitions")?;
            let want = assignment
                .get("partition")
                .and_then(Value::as_u64)
                .ok_or("assignment needs a partition")?;
            let got = assign(node_id, objective_id, &beacon(epoch, anchor), partitions)?;
            f.check(
                "partition",
                &format!("{node_id} of {partitions}"),
                got,
                want,
            );
            checked += 1;
        }
        for rank in case.get("ranks").and_then(Value::as_array).unwrap_or(&[]) {
            let key = str_of(rank, "key")?;
            f.check(
                "partition",
                &format!("settlement_rank {key}"),
                settlement_rank(epoch, anchor, key),
                str_of(rank, "rank")?.to_string(),
            );
            checked += 1;
        }
    }

    // -- the payout curve ---------------------------------------------------
    for case in section(&vectors, "ratchet")? {
        let spec = case.get("ratchet").unwrap_or(case);
        let ratchet = Ratchet::from_value(spec).map_err(|e| format!("ratchet: {e}"))?;
        for point in case.get("points").and_then(Value::as_array).unwrap_or(&[]) {
            let score = point
                .get("score")
                .and_then(Value::as_i64)
                .ok_or("ratchet point needs a score")?;
            if let Some(want) = point.get("progress").and_then(Value::as_u64) {
                f.check(
                    "ratchet",
                    &format!("progress at {score}"),
                    ratchet.progress(score),
                    want,
                );
            }
            if let Some(want) = point.get("cumulative").and_then(Value::as_u64) {
                f.check(
                    "ratchet",
                    &format!("cumulative at {score}"),
                    ratchet.cumulative(score),
                    want,
                );
            }
            checked += 1;
        }
    }

    if f.0.is_empty() {
        println!("conformance ok: {checked} vectors reproduced independently");
        Ok(())
    } else {
        for failure in &f.0 {
            println!("  {failure}");
        }
        Err(format!("{} vector(s) disagree", f.0.len()))
    }
}

fn audit(path: Option<&str>) -> Result<(), String> {
    let path = path.ok_or("expected a path to a log")?;
    let ledger = Ledger::open(path)?;
    let mut problems = ledger.verify_chain();

    // Every record must decode, re-encode to the same bytes, and -- when its
    // submitter names a key -- carry a signature that verifies. A record whose
    // canonical form changed on the way through is a record whose id moved.
    let mut records = 0usize;
    let mut signed = 0usize;
    for entry in ledger.entries() {
        let re_encoded = match entry.kind.as_str() {
            "objective" => Objective::from_value(&entry.payload)
                .map(|record| record.to_value())
                .map_err(|e| e.to_string()),
            "commitment" => Commitment::from_value(&entry.payload)
                .and_then(|record| {
                    record.verify_signature()?;
                    if record.signature.is_some() {
                        signed += 1;
                    }
                    Ok(record.to_value())
                })
                .map_err(|e| e.to_string()),
            "claim" => Claim::from_value(&entry.payload)
                .and_then(|record| {
                    record.verify_signature()?;
                    if record.signature.is_some() {
                        signed += 1;
                    }
                    Ok(record.to_value())
                })
                .map_err(|e| e.to_string()),
            // verdict, batch, frontier and friends are node-side bookkeeping
            // rather than submitted records; the chain check above still
            // covers them.
            _ => continue,
        };
        records += 1;
        match re_encoded {
            Ok(value) if value == entry.payload => {}
            Ok(_) => problems.push(format!(
                "entry {}: {} does not re-encode to its own bytes",
                entry.seq, entry.kind
            )),
            Err(error) => problems.push(format!("entry {}: {error}", entry.seq)),
        }
    }

    println!(
        "entries {}   records {records}   signed {signed}",
        ledger.len()
    );
    if let Some(root) = ledger.merkle_root() {
        println!("merkle  {root}");
    }
    if problems.is_empty() {
        println!("\nlog verified: chain intact, every record re-derived independently");
        Ok(())
    } else {
        for problem in &problems {
            println!("  ! {problem}");
        }
        Err(format!("{} problem(s)", problems.len()))
    }
}

// -- vector helpers ---------------------------------------------------------

fn section<'a>(vectors: &'a Value, name: &str) -> Result<&'a [Value], String> {
    vectors
        .get(name)
        .and_then(Value::as_array)
        .ok_or_else(|| format!("vectors need a {name} array"))
}

fn array<'a>(parent: &'a Value, name: &str) -> Result<&'a [Value], String> {
    Ok(parent.get(name).and_then(Value::as_array).unwrap_or(&[]))
}

fn str_of<'a>(value: &'a Value, name: &str) -> Result<&'a str, String> {
    value
        .get(name)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("vector needs a string {name:?}"))
}
