//! `proofwork-reference` — the independent checker.
//!
//! Two jobs:
//!
//! * `conformance <vectors.json>` — reproduce every frozen vector. These were
//!   generated by the Python reference that this crate replaces, which is the
//!   point: they are the surviving evidence from an implementation written in
//!   another language, and they keep proving the format is a format rather
//!   than a description of one program's behaviour.
//! * `audit <log.jsonl>` — re-derive a log the primary implementation wrote:
//!   chain integrity, record ids, signatures, Merkle root.

use std::process::ExitCode;

use proofwork_reference::canonical::{merkle_root, Value};
use proofwork_reference::frontier::Ratchet;
use proofwork_reference::ledger::Ledger;
use proofwork_reference::node::Node;
use proofwork_reference::partition::{assign, beacon, settlement_rank};
use proofwork_reference::records::{commitment_hash, Claim, Commitment, Objective};
use proofwork_reference::time::timestamp;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    // The command may sit behind global flags (`--log`, `--root`), so dispatch
    // on the first non-flag word rather than on argv[0].
    let command = args
        .iter()
        .enumerate()
        .find(|(index, arg)| {
            !arg.starts_with("--")
                && !matches!(
                    args.get(index.wrapping_sub(1)).map(String::as_str),
                    Some("--log") | Some("--root")
                )
        })
        .map(|(_, arg)| arg.as_str());
    let result = match command {
        Some("conformance") => conformance(
            args.iter()
                .position(|a| a == "conformance")
                .and_then(|at| args.get(at + 1))
                .map(String::as_str),
        ),
        Some("audit") | Some("post") | Some("commit") | Some("reveal") | Some("settle")
        | Some("log") | Some("decode") | Some("canon") => cli(&args),
        Some("--help") | Some("help") | None => {
            eprintln!(
                "proofwork-reference — an independent check on the primary implementation\n\n\
                 USAGE\n    \
                 proofwork-reference conformance <vectors.json>\n    \
                 proofwork-reference [--log P] [--root D] post <objective.json>\n    \
                 proofwork-reference [--log P] [--root D] commit <id> --submitter S --artifact F [--nonce N]\n    \
                 proofwork-reference [--log P] [--root D] reveal <id> --submitter S --artifact F --nonce N [--cites ID]\n    \
                 proofwork-reference [--log P] [--root D] settle\n    \
                 proofwork-reference [--log P] [--root D] audit\n"
            );
            return ExitCode::SUCCESS;
        }
        Some(other) => Err(format!("unknown command {other:?}")),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("proofwork-reference: {message}");
            ExitCode::FAILURE
        }
    }
}

fn read(path: Option<&str>, what: &str) -> Result<String, String> {
    let path = path.ok_or_else(|| format!("expected a path to {what}"))?;
    std::fs::read_to_string(path).map_err(|error| format!("cannot read {path}: {error}"))
}

/// Every failure is collected rather than returned at the first one: knowing
/// that four sections disagree tells you something different from knowing that
/// one does, and an implementer fixing a format bug wants the whole list.
struct Failures(Vec<String>);

impl Failures {
    fn check(
        &mut self,
        section: &str,
        label: &str,
        got: impl std::fmt::Debug,
        want: impl std::fmt::Debug,
    ) {
        let (got, want) = (format!("{got:?}"), format!("{want:?}"));
        if got != want {
            self.0.push(format!(
                "{section}: {label}\n    got  {got}\n    want {want}"
            ));
        }
    }
}

fn conformance(path: Option<&str>) -> Result<(), String> {
    let text = read(path, "conformance/vectors.json")?;
    let vectors = Value::from_json(&text).map_err(|e| e.to_string())?;
    let mut f = Failures(Vec::new());
    let mut checked = 0usize;

    // -- canonical encoding, the contract everything else rests on ----------
    for case in section(&vectors, "canonical")? {
        let value = case.get("value").ok_or("canonical case needs a value")?;
        let want_utf8 = str_of(case, "canonical_utf8")?;
        f.check(
            "canonical",
            want_utf8,
            value.canonical_string(),
            want_utf8.to_string(),
        );
        f.check(
            "canonical",
            &format!("digest of {want_utf8}"),
            value.digest(),
            str_of(case, "digest")?.to_string(),
        );
        // The decoder must round-trip its own encoder's output, or a log this
        // implementation wrote could not be read back by it.
        if let Ok(reparsed) = Value::from_json(&value.canonical_string()) {
            f.check(
                "canonical",
                &format!("round trip {want_utf8}"),
                reparsed,
                value.clone(),
            );
        } else {
            f.0.push(format!("canonical: {want_utf8} did not re-parse"));
        }
        checked += 1;
    }

    // -- merkle: the odd node is promoted, not duplicated -------------------
    for case in section(&vectors, "merkle")? {
        let leaves: Vec<String> = case
            .get("leaves")
            .and_then(Value::as_array)
            .ok_or("merkle case needs leaves")?
            .iter()
            .filter_map(|v| v.as_str().map(str::to_string))
            .collect();
        let want = case.get("root").and_then(Value::as_str).map(str::to_string);
        f.check(
            "merkle",
            &format!("{} leaves", leaves.len()),
            merkle_root(&leaves),
            want,
        );
        checked += 1;
    }

    // -- record identity ----------------------------------------------------
    let records = vectors
        .get("records")
        .ok_or("vectors need a records section")?;
    for case in array(records, "objectives")? {
        let record = case.get("record").ok_or("objective case needs a record")?;
        let objective = Objective::from_value(record).map_err(|e| format!("objective: {e}"))?;
        f.check(
            "records",
            "objective id",
            objective.id(),
            str_of(case, "id")?.to_string(),
        );
        // The canonical form must round-trip: decoding and re-encoding a
        // record has to reproduce it byte for byte, or an id moves when a
        // record is merely relayed.
        f.check(
            "records",
            "objective re-encode",
            objective.to_value(),
            record.clone(),
        );
        checked += 1;
    }
    for case in array(records, "commitments")? {
        let record = case.get("record").ok_or("commitment case needs a record")?;
        let commitment = Commitment::from_value(record).map_err(|e| format!("commitment: {e}"))?;
        f.check(
            "records",
            "commitment id",
            commitment.id(),
            str_of(case, "id")?.to_string(),
        );
        f.check(
            "records",
            "commitment re-encode",
            commitment.to_value(),
            record.clone(),
        );
        checked += 1;
    }
    for case in array(records, "claims")? {
        let record = case.get("record").ok_or("claim case needs a record")?;
        let claim = Claim::from_value(record).map_err(|e| format!("claim: {e}"))?;
        f.check(
            "records",
            "claim id",
            claim.id(),
            str_of(case, "id")?.to_string(),
        );
        f.check(
            "records",
            "claim re-encode",
            claim.to_value(),
            record.clone(),
        );
        f.check(
            "records",
            "claim artifact_id",
            claim.artifact_id(),
            str_of(case, "artifact_id")?.to_string(),
        );
        f.check(
            "records",
            "commitment_hash",
            commitment_hash(
                &claim.objective_id,
                &claim.submitter,
                &claim.artifact,
                &claim.nonce,
            ),
            str_of(case, "commitment_hash")?.to_string(),
        );
        checked += 1;
    }

    // -- the settlement beacon and work assignment --------------------------
    for case in section(&vectors, "partition")? {
        let anchor = str_of(case, "anchor")?;
        let epoch = case.get("epoch").and_then(Value::as_u64).unwrap_or(0);
        if let Some(want) = case.get("beacon").and_then(Value::as_str) {
            f.check(
                "partition",
                "beacon",
                beacon(epoch, anchor),
                want.to_string(),
            );
        }
        for assignment in case
            .get("assignments")
            .and_then(Value::as_array)
            .unwrap_or(&[])
        {
            let node_id = str_of(assignment, "node_id")?;
            let objective_id = str_of(assignment, "objective_id")?;
            let partitions = assignment
                .get("partitions")
                .and_then(Value::as_u64)
                .ok_or("assignment needs partitions")?;
            let want = assignment
                .get("partition")
                .and_then(Value::as_u64)
                .ok_or("assignment needs a partition")?;
            let got = assign(node_id, objective_id, &beacon(epoch, anchor), partitions)?;
            f.check(
                "partition",
                &format!("{node_id} of {partitions}"),
                got,
                want,
            );
            checked += 1;
        }
        for rank in case.get("ranks").and_then(Value::as_array).unwrap_or(&[]) {
            let key = str_of(rank, "key")?;
            f.check(
                "partition",
                &format!("settlement_rank {key}"),
                settlement_rank(epoch, anchor, key),
                str_of(rank, "rank")?.to_string(),
            );
            checked += 1;
        }
    }

    // -- the payout curve ---------------------------------------------------
    for case in section(&vectors, "ratchet")? {
        let spec = case.get("ratchet").unwrap_or(case);
        let ratchet = Ratchet::from_value(spec).map_err(|e| format!("ratchet: {e}"))?;
        for point in case.get("points").and_then(Value::as_array).unwrap_or(&[]) {
            let score = point
                .get("score")
                .and_then(Value::as_i64)
                .ok_or("ratchet point needs a score")?;
            if let Some(want) = point.get("progress").and_then(Value::as_u64) {
                f.check(
                    "ratchet",
                    &format!("progress at {score}"),
                    ratchet.progress(score),
                    want,
                );
            }
            if let Some(want) = point.get("cumulative").and_then(Value::as_u64) {
                f.check(
                    "ratchet",
                    &format!("cumulative at {score}"),
                    ratchet.cumulative(score),
                    want,
                );
            }
            checked += 1;
        }
    }

    if f.0.is_empty() {
        println!("conformance ok: {checked} vectors reproduced independently");
        Ok(())
    } else {
        for failure in &f.0 {
            println!("  {failure}");
        }
        Err(format!("{} vector(s) disagree", f.0.len()))
    }
}

// -- vector helpers ---------------------------------------------------------

fn section<'a>(vectors: &'a Value, name: &str) -> Result<&'a [Value], String> {
    vectors
        .get(name)
        .and_then(Value::as_array)
        .ok_or_else(|| format!("vectors need a {name} array"))
}

fn array<'a>(parent: &'a Value, name: &str) -> Result<&'a [Value], String> {
    Ok(parent.get(name).and_then(Value::as_array).unwrap_or(&[]))
}

fn str_of<'a>(value: &'a Value, name: &str) -> Result<&'a str, String> {
    value
        .get(name)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("vector needs a string {name:?}"))
}

// -- the CLI ----------------------------------------------------------------
//
// The same surface `scripts/interop.sh` drives against the primary
// implementation, so the two can each produce a log the other audits. That
// round trip is the whole claim: "anyone can re-derive every settled result"
// means nothing if it means "anyone running my code".

fn cli(args: &[String]) -> Result<(), String> {
    let mut log = String::from("proofwork.jsonl");
    let mut root = String::from(".");
    let mut rest: Vec<String> = Vec::new();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--log" => {
                log = args.get(i + 1).cloned().ok_or("--log needs a path")?;
                i += 2;
            }
            "--root" => {
                root = args.get(i + 1).cloned().ok_or("--root needs a path")?;
                i += 2;
            }
            other => {
                rest.push(other.to_string());
                i += 1;
            }
        }
    }
    let command = rest.first().cloned().unwrap_or_default();
    let flag = |name: &str| -> Option<String> {
        rest.iter()
            .position(|a| a == name)
            .and_then(|at| rest.get(at + 1).cloned())
    };
    let positional = rest.get(1).filter(|a| !a.starts_with("--")).cloned();

    let mut node = Node::new(Ledger::open(&log)?, &root);
    let ts = timestamp();

    match command.as_str() {
        "post" => {
            let path = positional.ok_or("post needs an objective JSON file")?;
            let value =
                Value::from_json(&read(Some(&path), "an objective")?).map_err(|e| e.to_string())?;
            let objective = Objective::from_value(&value).map_err(|e| e.to_string())?;
            let id = node.post_objective(&objective, &ts)?;
            // Field 2 is the id, and interop.sh reads it with awk.
            println!("objective {id}");
            println!(
                "  reward {}  verifier {}",
                objective.reward,
                objective.verifier_kind().unwrap_or("?")
            );
        }
        "commit" => {
            let objective_id = positional.ok_or("commit needs an objective id")?;
            let submitter = flag("--submitter").ok_or("commit needs --submitter")?;
            let artifact = Value::from_json(&read(flag("--artifact").as_deref(), "an artifact")?)
                .map_err(|e| e.to_string())?;
            let nonce = flag("--nonce")
                .filter(|n| !n.is_empty())
                .unwrap_or_else(random_nonce);
            let hash = commitment_hash(&objective_id, &submitter, &artifact, &nonce);
            let commitment = Commitment {
                objective_id,
                submitter,
                hash: hash.clone(),
                created_at: ts.clone(),
                signature: None,
            };
            node.commit(&commitment, &ts)?;
            println!("committed {}", proofwork_reference::canonical::short(&hash));
            println!("  nonce {nonce}   <- keep this; you need it to reveal");
        }
        "reveal" => {
            let objective_id = positional.ok_or("reveal needs an objective id")?;
            let submitter = flag("--submitter").ok_or("reveal needs --submitter")?;
            let artifact = Value::from_json(&read(flag("--artifact").as_deref(), "an artifact")?)
                .map_err(|e| e.to_string())?;
            let nonce = flag("--nonce").ok_or("reveal needs --nonce")?;
            let cites: Vec<String> = rest
                .iter()
                .enumerate()
                .filter(|(_, a)| a.as_str() == "--cites")
                .filter_map(|(at, _)| rest.get(at + 1).cloned())
                .collect();
            let claim = Claim {
                objective_id,
                submitter,
                artifact,
                nonce,
                created_at: ts.clone(),
                cites,
                signature: None,
            };
            claim.validate().map_err(|e| e.to_string())?;
            let outcome = node.reveal(&claim, &ts)?;
            println!("claim {}", outcome.claim_id);
            println!(
                "  verdict  {}: {}",
                outcome.verdict.status.as_str(),
                outcome.verdict.detail
            );
            println!("  {}", outcome.note);
        }
        "settle" => {
            let outcomes = node.settle_at(&ts)?;
            if outcomes.is_empty() {
                println!("no batch was due");
            }
            for outcome in outcomes {
                println!(
                    "claim {}\n  settled  {}  reward {}  ({})",
                    outcome.claim_id, outcome.settled, outcome.reward, outcome.note
                );
            }
        }
        // Decode a single record and say whether it is admissible, without a
        // log and without writing anything. Useful on its own for checking a
        // record before posting it, and it is the surface
        // `scripts/differential.sh` drives to prove the two implementations
        // classify every record the same way.
        "decode" => {
            let kind = positional.ok_or("decode needs a record kind")?;
            let path = flag("--record").ok_or("decode needs --record <file>")?;
            let value =
                Value::from_json(&read(Some(&path), "a record")?).map_err(|e| e.to_string())?;
            match decode_record(&kind, &value) {
                Ok(id) => println!("ok {id}"),
                Err(reason) => {
                    println!("refused");
                    eprintln!("  {reason}");
                    return Err("record refused".into());
                }
            }
        }
        // Canonicalize one JSON value: the format contract at its narrowest.
        // `scripts/fuzz-differential.sh` drives this on random input, which is
        // where an encoder disagreement shows up before it ever reaches a
        // record.
        "canon" => {
            let path = flag("--input").ok_or("canon needs --input <file>")?;
            match Value::from_json(&read(Some(&path), "a JSON value")?) {
                Ok(value) => println!("ok {} {}", value.digest(), value.canonical_string()),
                Err(error) => {
                    println!("refused");
                    eprintln!("  {error}");
                    return Err("input refused".into());
                }
            }
        }
        "log" => {
            for entry in node.ledger.entries() {
                println!("{:>4}  {:<12} {}", entry.seq, entry.kind, entry.hash);
            }
        }
        "audit" => {
            // `rerun` on by default: re-running the pinned verifiers is the
            // thing that makes an audit an audit rather than a checksum.
            let problems = node.audit(!rest.iter().any(|a| a == "--no-rerun"));
            println!("entries {}", node.ledger.len());
            if let Some(root) = node.ledger.merkle_root() {
                println!("merkle  {root}");
            }
            if problems.is_empty() {
                println!("\nlog verified: chain intact, every settled claim re-verified");
            } else {
                for problem in &problems {
                    println!("  ! {problem}");
                }
                return Err(format!("{} problem(s)", problems.len()));
            }
        }
        other => return Err(format!("unknown command {other:?}")),
    }
    Ok(())
}

/// Not cryptographically chosen: this is a reference implementation and its
/// nonces protect nothing anybody is paid for. The primary implementation uses
/// the OS RNG.
fn random_nonce() -> String {
    let seed = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    proofwork_reference::canonical::digest_bytes(&seed.to_le_bytes())
        .trim_start_matches("sha256:")
        .chars()
        .take(32)
        .collect()
}

/// Decode one record of `kind`, returning its id or why it is inadmissible.
///
/// Signatures are checked here too: a record naming a key it cannot prove is
/// inadmissible, not merely unsigned.
fn decode_record(kind: &str, value: &Value) -> Result<String, String> {
    match kind {
        "objective" => Objective::from_value(value)
            .map(|record| record.id())
            .map_err(|e| e.to_string()),
        "commitment" => Commitment::from_value(value)
            .and_then(|record| {
                record.verify_signature()?;
                Ok(record.id())
            })
            .map_err(|e| e.to_string()),
        "claim" => Claim::from_value(value)
            .and_then(|record| {
                record.verify_signature()?;
                Ok(record.id())
            })
            .map_err(|e| e.to_string()),
        other => Err(format!("unknown record kind {other:?}")),
    }
}
