//! `cairn-reference` — the independent checker.
//!
//! Two jobs:
//!
//! * `conformance <vectors.json>` — reproduce every frozen vector. These were
//!   generated by the Python reference that this crate replaces, which is the
//!   point: they are the surviving evidence from an implementation written in
//!   another language, and they keep proving the format is a format rather
//!   than a description of one program's behaviour.
//! * `signed-records <signed-records.json>` and `signatures <signatures.json>`
//!   — the same, for the two vector files that cover signing. They are separate
//!   commands because they are separate files, and they exist because when the
//!   Python reference went away those two lost their only independent checker.
//!   A signature is inside the record, so it is inside the id: an implementation
//!   that got the signing payload right and the *id* wrong would settle a
//!   different claim while verifying every signature perfectly.
//! * `audit <log.jsonl>` — re-derive a log the primary implementation wrote:
//!   chain integrity, record ids, signatures, Merkle root.

use std::io::Write as _;
use std::process::ExitCode;

use cairn_reference::attribution::{flow, FlowParams};
use cairn_reference::canonical::{merkle_root, Value};
use cairn_reference::frontier::Ratchet;
use cairn_reference::ledger::{Ledger, Proof};
use cairn_reference::node::Node;
use cairn_reference::partition::{assign, beacon, settlement_rank};
use cairn_reference::records::{
    commitment_hash, Claim, ClaimRelation, Commitment, CommitteeShare, Objective, PeerRecord,
};
use cairn_reference::time::timestamp;

/// Write one line, treating a closed pipe as the end of output.
///
/// `println!` **panics** when the reader has gone away, and
/// `cairn-reference post … | head -1` is the everyday way to make that
/// happen -- `scripts/interop.sh` does exactly that to pick an objective id out
/// of field 2. `post` prints two lines, so whether the panic fires is a race
/// between this process reaching the second line and `head` exiting after the
/// first. It is quiet on an idle machine and loses under load, which is the
/// worst shape a bug can have: it looked like a flaky script.
///
/// The primary implementation has had this fix and a `//!` paragraph explaining
/// it since before this crate existed. It never made it across, and nothing
/// noticed, because the divergence is in output plumbing rather than in the
/// rules -- the one part of the two implementations nothing compares.
macro_rules! say {
    ($($arg:tt)*) => {{
        let _ = writeln!(std::io::stdout(), $($arg)*);
    }};
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    // The command may sit behind global flags (`--log`, `--root`), so dispatch
    // on the first non-flag word rather than on argv[0].
    let command = args
        .iter()
        .enumerate()
        .find(|(index, arg)| {
            !arg.starts_with("--")
                && !matches!(
                    args.get(index.wrapping_sub(1)).map(String::as_str),
                    Some("--log") | Some("--root")
                )
        })
        .map(|(_, arg)| arg.as_str());
    let result = match command {
        Some("conformance") => conformance(after(&args, "conformance")),
        Some("signed-records") => signed_records(after(&args, "signed-records")),
        Some("signatures") => signatures(after(&args, "signatures")),
        Some("drand-verify") => {
            drand_verify(after(&args, "drand-verify"), after(&args, "--signature"))
        }
        Some("audit") | Some("post") | Some("commit") | Some("reveal") | Some("settle")
        | Some("log") | Some("decode") | Some("canon") | Some("prove") | Some("check") => {
            cli(&args)
        }
        Some("--help") | Some("help") | None => {
            eprintln!(
                "cairn-reference — an independent check on the primary implementation\n\n\
                 USAGE\n    \
                 cairn-reference conformance <vectors.json>\n    \
                 cairn-reference signed-records <signed-records.json>\n    \
                 cairn-reference signatures <signatures.json>\n    \
                 cairn-reference drand-verify <round> --signature <hex>\n    \
                 cairn-reference [--log P] [--root D] post <objective.json>\n    \
                 cairn-reference [--log P] [--root D] commit <id> --submitter S --artifact F [--nonce N]\n    \
                 cairn-reference [--log P] [--root D] reveal <id> --submitter S --artifact F --nonce N [--cites ID]\n    \
                 cairn-reference [--log P] [--root D] settle\n    \
                 cairn-reference [--log P] [--root D] audit\n    \
                 cairn-reference [--log P] prove <seq> [--out FILE]\n    \
                 cairn-reference check <proof.json> --merkle-root <sha256:...>\n"
            );
            return ExitCode::SUCCESS;
        }
        Some(other) => Err(format!("unknown command {other:?}")),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("cairn-reference: {message}");
            ExitCode::FAILURE
        }
    }
}

fn read(path: Option<&str>, what: &str) -> Result<String, String> {
    let path = path.ok_or_else(|| format!("expected a path to {what}"))?;
    std::fs::read_to_string(path).map_err(|error| format!("cannot read {path}: {error}"))
}

/// The argument following `word`, wherever `word` sits in the argument list.
/// Does a quicknet signature verify, according to *this* implementation?
///
/// A command so that `scripts/differential.sh` can put the same signatures in
/// front of both implementations and require the same answer. The pairing is
/// the one check in this protocol where two correct-looking programs can be
/// made to disagree -- the two run different BLS libraries deliberately -- and
/// a claim that they agree is worth nothing unless something asks them both.
///
/// Exit 0 for verified and 1 for anything else, so a shell can branch on it
/// without parsing prose.
fn drand_verify(round: Option<&str>, signature: Option<&str>) -> Result<(), String> {
    let round = round.ok_or("expected a round number")?;
    let round: u64 = round
        .parse()
        .map_err(|_| format!("not a round number: {round:?}"))?;
    let signature = signature.ok_or("expected --signature <hex>")?;
    if cairn_reference::drand::verify(round, signature) {
        println!("round {round}: verified");
        Ok(())
    } else {
        println!("round {round}: does not verify");
        Err(format!("round {round} is not carried by that signature"))
    }
}

fn after<'a>(args: &'a [String], word: &str) -> Option<&'a str> {
    args.iter()
        .position(|arg| arg == word)
        .and_then(|at| args.get(at + 1))
        .map(String::as_str)
}

/// Every failure is collected rather than returned at the first one: knowing
/// that four sections disagree tells you something different from knowing that
/// one does, and an implementer fixing a format bug wants the whole list.
struct Failures(Vec<String>);

impl Failures {
    fn check(
        &mut self,
        section: &str,
        label: &str,
        got: impl std::fmt::Debug,
        want: impl std::fmt::Debug,
    ) {
        let (got, want) = (format!("{got:?}"), format!("{want:?}"));
        if got != want {
            self.0.push(format!(
                "{section}: {label}\n    got  {got}\n    want {want}"
            ));
        }
    }
}

fn conformance(path: Option<&str>) -> Result<(), String> {
    let text = read(path, "conformance/vectors.json")?;
    let vectors = Value::from_json(&text).map_err(|e| e.to_string())?;
    let mut f = Failures(Vec::new());
    let mut checked = 0usize;

    // -- canonical encoding, the contract everything else rests on ----------
    for case in section(&vectors, "canonical")? {
        let value = case.get("value").ok_or("canonical case needs a value")?;
        let want_utf8 = str_of(case, "canonical_utf8")?;
        f.check(
            "canonical",
            want_utf8,
            value.canonical_string(),
            want_utf8.to_string(),
        );
        f.check(
            "canonical",
            &format!("digest of {want_utf8}"),
            value.digest(),
            str_of(case, "digest")?.to_string(),
        );
        // The decoder must round-trip its own encoder's output, or a log this
        // implementation wrote could not be read back by it.
        if let Ok(reparsed) = Value::from_json(&value.canonical_string()) {
            f.check(
                "canonical",
                &format!("round trip {want_utf8}"),
                reparsed,
                value.clone(),
            );
        } else {
            f.0.push(format!("canonical: {want_utf8} did not re-parse"));
        }
        checked += 1;
    }

    // -- attribution: who gets paid what ------------------------------------
    //
    // The section nothing checked until now. A canonical-encoding divergence is
    // loud -- two nodes compute different ids and nothing settles. A payout
    // divergence is silent, and both nodes carry on having paid different
    // people different amounts.
    {
        let section = vectors
            .get("attribution")
            .ok_or("vectors need an attribution section")?;
        let root = str_of(section, "root")?;
        let mut claims: std::collections::BTreeMap<String, Claim> =
            std::collections::BTreeMap::new();
        for value in section
            .get("claims")
            .and_then(Value::as_array)
            .ok_or("attribution needs claims")?
        {
            let claim = Claim::from_value(value).map_err(|e| format!("attribution claim: {e}"))?;
            claims.insert(claim.id(), claim);
        }
        for case in array(section, "cases")? {
            let amount = case
                .get("amount")
                .and_then(Value::as_u64)
                .ok_or("case needs an amount")?;
            let params = FlowParams {
                delta_num: case
                    .get("delta_num")
                    .and_then(Value::as_u64)
                    .ok_or("case needs delta_num")?,
                delta_den: case
                    .get("delta_den")
                    .and_then(Value::as_u64)
                    .ok_or("case needs delta_den")?,
                max_depth: case
                    .get("max_depth")
                    .and_then(Value::as_u64)
                    .ok_or("case needs max_depth")? as u32,
            };
            let got = flow(root, amount, &claims, &params);
            let mut want: std::collections::BTreeMap<String, u64> =
                std::collections::BTreeMap::new();
            if let Some(Value::Object(map)) = case.get("payouts") {
                for (who, units) in map {
                    want.insert(
                        who.clone(),
                        units.as_u64().ok_or("a payout must be an integer")?,
                    );
                }
            }
            f.check(
                "attribution",
                &format!(
                    "amount {amount} delta {}/{} depth {}",
                    params.delta_num, params.delta_den, params.max_depth
                ),
                &got,
                &want,
            );
            // Conservation, checked independently of the vector: the values
            // must sum to exactly the amount settled. A vector and an
            // implementation that agreed on a wrong split would both pass the
            // check above.
            let total: u64 = got.values().sum();
            if total != amount {
                f.0.push(format!(
                    "attribution: amount {amount} split into {total}, which \
                     invents or destroys {} unit(s)",
                    total.abs_diff(amount)
                ));
            }
            checked += 1;
        }
    }

    // -- merkle: the odd node is promoted, not duplicated -------------------
    for case in section(&vectors, "merkle")? {
        let leaves: Vec<String> = case
            .get("leaves")
            .and_then(Value::as_array)
            .ok_or("merkle case needs leaves")?
            .iter()
            .filter_map(|v| v.as_str().map(str::to_string))
            .collect();
        let want = case.get("root").and_then(Value::as_str).map(str::to_string);
        f.check(
            "merkle",
            &format!("{} leaves", leaves.len()),
            merkle_root(&leaves),
            want,
        );
        checked += 1;
    }

    // -- record identity ----------------------------------------------------
    let records = vectors
        .get("records")
        .ok_or("vectors need a records section")?;
    for case in array(records, "objectives")? {
        let record = case.get("record").ok_or("objective case needs a record")?;
        let objective = Objective::from_value(record).map_err(|e| format!("objective: {e}"))?;
        f.check(
            "records",
            "objective id",
            objective.id(),
            str_of(case, "id")?.to_string(),
        );
        // The canonical form must round-trip: decoding and re-encoding a
        // record has to reproduce it byte for byte, or an id moves when a
        // record is merely relayed.
        f.check(
            "records",
            "objective re-encode",
            objective.to_value(),
            record.clone(),
        );
        checked += 1;
    }
    for case in array(records, "commitments")? {
        let record = case.get("record").ok_or("commitment case needs a record")?;
        let commitment = Commitment::from_value(record).map_err(|e| format!("commitment: {e}"))?;
        f.check(
            "records",
            "commitment id",
            commitment.id(),
            str_of(case, "id")?.to_string(),
        );
        f.check(
            "records",
            "commitment re-encode",
            commitment.to_value(),
            record.clone(),
        );
        checked += 1;
    }
    for case in array(records, "claims")? {
        let record = case.get("record").ok_or("claim case needs a record")?;
        let claim = Claim::from_value(record).map_err(|e| format!("claim: {e}"))?;
        f.check(
            "records",
            "claim id",
            claim.id(),
            str_of(case, "id")?.to_string(),
        );
        f.check(
            "records",
            "claim re-encode",
            claim.to_value(),
            record.clone(),
        );
        f.check(
            "records",
            "claim artifact_id",
            claim.artifact_id(),
            str_of(case, "artifact_id")?.to_string(),
        );
        f.check(
            "records",
            "commitment_hash",
            commitment_hash(
                &claim.objective_id,
                &claim.submitter,
                &claim.artifact,
                &claim.nonce,
            ),
            str_of(case, "commitment_hash")?.to_string(),
        );
        checked += 1;
    }

    // -- the settlement beacon and work assignment --------------------------
    for case in section(&vectors, "partition")? {
        let anchor = str_of(case, "anchor")?;
        let epoch = case.get("epoch").and_then(Value::as_u64).unwrap_or(0);
        if let Some(want) = case.get("beacon").and_then(Value::as_str) {
            f.check(
                "partition",
                "beacon",
                beacon(epoch, anchor),
                want.to_string(),
            );
        }
        for assignment in case
            .get("assignments")
            .and_then(Value::as_array)
            .unwrap_or(&[])
        {
            let node_id = str_of(assignment, "node_id")?;
            let objective_id = str_of(assignment, "objective_id")?;
            let partitions = assignment
                .get("partitions")
                .and_then(Value::as_u64)
                .ok_or("assignment needs partitions")?;
            let want = assignment
                .get("partition")
                .and_then(Value::as_u64)
                .ok_or("assignment needs a partition")?;
            let got = assign(node_id, objective_id, &beacon(epoch, anchor), partitions)?;
            f.check(
                "partition",
                &format!("{node_id} of {partitions}"),
                got,
                want,
            );
            checked += 1;
        }
        for rank in case.get("ranks").and_then(Value::as_array).unwrap_or(&[]) {
            let key = str_of(rank, "key")?;
            f.check(
                "partition",
                &format!("settlement_rank {key}"),
                settlement_rank(epoch, anchor, key),
                str_of(rank, "rank")?.to_string(),
            );
            checked += 1;
        }
    }

    // -- the payout curve ---------------------------------------------------
    for case in section(&vectors, "ratchet")? {
        let spec = case.get("ratchet").unwrap_or(case);
        let ratchet = Ratchet::from_value(spec).map_err(|e| format!("ratchet: {e}"))?;
        for point in case.get("points").and_then(Value::as_array).unwrap_or(&[]) {
            let score = point
                .get("score")
                .and_then(Value::as_i64)
                .ok_or("ratchet point needs a score")?;
            if let Some(want) = point.get("progress").and_then(Value::as_u64) {
                f.check(
                    "ratchet",
                    &format!("progress at {score}"),
                    ratchet.progress(score),
                    want,
                );
            }
            if let Some(want) = point.get("cumulative").and_then(Value::as_u64) {
                f.check(
                    "ratchet",
                    &format!("cumulative at {score}"),
                    ratchet.cumulative(score),
                    want,
                );
            }
            checked += 1;
        }
    }

    if f.0.is_empty() {
        say!("conformance ok: {checked} vectors reproduced independently");
        Ok(())
    } else {
        for failure in &f.0 {
            say!("  {failure}");
        }
        Err(format!("{} vector(s) disagree", f.0.len()))
    }
}

// -- vector helpers ---------------------------------------------------------

/// Reproduce `conformance/signed-records.json`.
///
/// One case per record kind, each holding the record, its canonical bytes, and
/// its id. All three are checked, and the third is the one that matters: the
/// signature is a field of the record, so it is inside the digest. An
/// implementation that agreed about the signing payload and disagreed about the
/// *id* would verify every signature perfectly and still settle a different
/// claim.
fn signed_records(path: Option<&str>) -> Result<(), String> {
    let text = read(path, "conformance/signed-records.json")?;
    let cases = Value::from_json(&text).map_err(|e| e.to_string())?;
    let Value::Object(by_kind) = &cases else {
        return Err(String::from("signed-records.json must be an object"));
    };
    let mut f = Failures(Vec::new());
    let mut checked = 0usize;

    for (kind, case) in by_kind {
        let record = case
            .get("record")
            .ok_or_else(|| format!("{kind}: case needs a record"))?;
        let want_canonical = str_of(case, "canonical")?;
        let want_id = str_of(case, "id")?;

        // Decoded and re-encoded rather than hashed as given, so this exercises
        // the reader too: a decoder that dropped `signature` would still
        // reproduce the bytes if they were hashed straight from the file.
        let (canonical, id, verified) = match kind.as_str() {
            "commitment" => {
                let commitment = Commitment::from_value(record).map_err(|e| e.0)?;
                (
                    commitment.to_value().canonical_string(),
                    commitment.id(),
                    commitment.verify_signature(),
                )
            }
            "claim" => {
                let claim = Claim::from_value(record).map_err(|e| e.0)?;
                (
                    claim.to_value().canonical_string(),
                    claim.id(),
                    claim.verify_signature(),
                )
            }
            other => return Err(format!("unknown record kind {other:?}")),
        };
        f.check(kind, "canonical", &canonical, want_canonical.to_string());
        f.check(kind, "id", &id, want_id.to_string());
        // And the signature really verifies. A vector whose signature was
        // wrong would still round-trip through the two checks above, which
        // would make this file a test of the encoder alone.
        f.check(kind, "signature verifies", verified.is_ok(), true);
        checked += 1;
    }

    report(f, checked, "signed record")
}

/// Reproduce `conformance/signatures.json`: raw ed25519 verification.
///
/// The one vector file that flows the other way — these were produced here and
/// checked by an implementation that shared no code with `ed25519-dalek`. What
/// they pin is `verify_strict` behaviour, so a rebuild against a library that
/// quietly accepted a small-order key or a non-canonical `s` would show up.
fn signatures(path: Option<&str>) -> Result<(), String> {
    let text = read(path, "conformance/signatures.json")?;
    let cases = Value::from_json(&text).map_err(|e| e.to_string())?;
    let Value::Array(cases) = &cases else {
        return Err(String::from("signatures.json must be an array"));
    };
    let mut f = Failures(Vec::new());
    let mut checked = 0usize;

    for (index, case) in cases.iter().enumerate() {
        let message = unhex(str_of(case, "message_hex")?)
            .ok_or_else(|| format!("case {index}: message_hex is not hex"))?;
        let key_hex = str_of(case, "public_key")?;
        let signature_hex = str_of(case, "signature")?;
        // `valid` absent means the case is a positive one. Absent and `false`
        // are not interchangeable anywhere in this format, and a negative
        // vector that silently read as positive would invert the whole check.
        let want = case
            .get("valid")
            .map(|value| matches!(value, Value::Bool(true)))
            .unwrap_or(true);

        let verified = match (
            cairn_reference::sig::public_key(key_hex),
            cairn_reference::sig::signature(signature_hex),
        ) {
            (Some(key), Some(signature)) => {
                cairn_reference::sig::verify(&key, &message, &signature)
            }
            // A key or signature this implementation cannot even parse is a
            // failure to verify, not an error: that is exactly what a negative
            // vector for a malformed key is testing.
            _ => false,
        };
        f.check("signatures", &format!("case {index}"), verified, want);
        checked += 1;
    }

    report(f, checked, "signature")
}

fn unhex(text: &str) -> Option<Vec<u8>> {
    if !text.len().is_multiple_of(2) {
        return None;
    }
    let mut out = Vec::with_capacity(text.len() / 2);
    let bytes = text.as_bytes();
    for pair in bytes.chunks(2) {
        let value = |byte: u8| match byte {
            b'0'..=b'9' => Some(byte - b'0'),
            b'a'..=b'f' => Some(byte - b'a' + 10),
            b'A'..=b'F' => Some(byte - b'A' + 10),
            _ => None,
        };
        out.push((value(pair[0])? << 4) | value(pair[1])?);
    }
    Some(out)
}

fn report(f: Failures, checked: usize, noun: &str) -> Result<(), String> {
    if f.0.is_empty() {
        say!("conformance ok: {checked} {noun} vector(s) reproduced independently");
        Ok(())
    } else {
        for failure in &f.0 {
            say!("  {failure}");
        }
        Err(format!("{} vector(s) disagree", f.0.len()))
    }
}

fn section<'a>(vectors: &'a Value, name: &str) -> Result<&'a [Value], String> {
    vectors
        .get(name)
        .and_then(Value::as_array)
        .ok_or_else(|| format!("vectors need a {name} array"))
}

fn array<'a>(parent: &'a Value, name: &str) -> Result<&'a [Value], String> {
    Ok(parent.get(name).and_then(Value::as_array).unwrap_or(&[]))
}

fn str_of<'a>(value: &'a Value, name: &str) -> Result<&'a str, String> {
    value
        .get(name)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("vector needs a string {name:?}"))
}

// -- the CLI ----------------------------------------------------------------
//
// The same surface `scripts/interop.sh` drives against the primary
// implementation, so the two can each produce a log the other audits. That
// round trip is the whole claim: "anyone can re-derive every settled result"
// means nothing if it means "anyone running my code".

fn cli(args: &[String]) -> Result<(), String> {
    let mut log = String::from("cairn.jsonl");
    let mut root = String::from(".");
    let mut rest: Vec<String> = Vec::new();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--log" => {
                log = args.get(i + 1).cloned().ok_or("--log needs a path")?;
                i += 2;
            }
            "--root" => {
                root = args.get(i + 1).cloned().ok_or("--root needs a path")?;
                i += 2;
            }
            other => {
                rest.push(other.to_string());
                i += 1;
            }
        }
    }
    let command = rest.first().cloned().unwrap_or_default();
    let flag = |name: &str| -> Option<String> {
        rest.iter()
            .position(|a| a == name)
            .and_then(|at| rest.get(at + 1).cloned())
    };
    let positional = rest.get(1).filter(|a| !a.starts_with("--")).cloned();

    // Before the log is opened, because this command must not need one. A
    // light client checking a proof holds a root and nothing else; a `check`
    // that quietly read a log would be testing something easier than the thing
    // the primary implementation claims to do.
    if command == "check" {
        let path = positional.ok_or("check needs a proof JSON file")?;
        // `--merkle-root`, not `--root`: the latter is the global flag naming
        // the bundle directory, and the argument parser above eats it wherever
        // it appears. Same spelling as the primary implementation, for the
        // same reason.
        let want = flag("--merkle-root").ok_or("check needs --merkle-root <sha256:...>")?;
        let value = Value::from_json(&read(Some(&path), "a proof")?).map_err(|e| e.to_string())?;
        let proof = Proof::from_value(&value)?;
        proof.check(&want)?;
        say!(
            "proof ok: entry {} ({}) is in the log rooted at {}",
            proof.entry.seq,
            proof.entry.kind,
            cairn_reference::canonical::short(&want)
        );
        say!(
            "  {} entries, {} hashes checked",
            proof.inclusion.leaves,
            proof.inclusion.siblings.len()
        );
        return Ok(());
    }

    let mut node = Node::new(Ledger::open(&log)?, &root);
    let ts = timestamp();

    match command.as_str() {
        "post" => {
            let path = positional.ok_or("post needs an objective JSON file")?;
            let value =
                Value::from_json(&read(Some(&path), "an objective")?).map_err(|e| e.to_string())?;
            let objective = Objective::from_value(&value).map_err(|e| e.to_string())?;
            let id = node.post_objective(&objective, &ts)?;
            // Field 2 is the id, and interop.sh reads it with awk.
            say!("objective {id}");
            say!(
                "  reward {}  verifier {}",
                objective.reward,
                objective.verifier_kind().unwrap_or("?")
            );
        }
        "commit" => {
            let objective_id = positional.ok_or("commit needs an objective id")?;
            let submitter = flag("--submitter").ok_or("commit needs --submitter")?;
            let artifact = Value::from_json(&read(flag("--artifact").as_deref(), "an artifact")?)
                .map_err(|e| e.to_string())?;
            let nonce = flag("--nonce")
                .filter(|n| !n.is_empty())
                .unwrap_or_else(random_nonce);
            let hash = commitment_hash(&objective_id, &submitter, &artifact, &nonce);
            let commitment = Commitment {
                objective_id,
                submitter,
                hash: hash.clone(),
                created_at: ts.clone(),
                // This CLI writes plain commit-reveal. Sealing needs a McEliece
                // key per committee member, which this crate deliberately does
                // not implement -- it audits envelopes rather than building
                // them, and carries the field opaquely so the encoding still
                // agrees.
                envelope: None,
                signature: None,
            };
            node.commit(&commitment, &ts)?;
            say!("committed {}", cairn_reference::canonical::short(&hash));
            say!("  nonce {nonce}   <- keep this; you need it to reveal");
        }
        "reveal" => {
            let objective_id = positional.ok_or("reveal needs an objective id")?;
            let submitter = flag("--submitter").ok_or("reveal needs --submitter")?;
            let artifact = Value::from_json(&read(flag("--artifact").as_deref(), "an artifact")?)
                .map_err(|e| e.to_string())?;
            let nonce = flag("--nonce").ok_or("reveal needs --nonce")?;
            let cites: Vec<String> = rest
                .iter()
                .enumerate()
                .filter(|(_, a)| a.as_str() == "--cites")
                .filter_map(|(at, _)| rest.get(at + 1).cloned())
                .collect();
            // `--relates <kind>:<target>`, repeatable. Present so this crate can
            // *write* a claim carrying relations and not only read one: interop
            // that exercises a field in one direction proves the encoder and the
            // decoder of a single implementation agree, which they always do.
            let mut relations = Vec::new();
            for (at, _) in rest.iter().enumerate().filter(|(_, a)| *a == "--relates") {
                let spec = rest.get(at + 1).ok_or("--relates needs <kind>:<target>")?;
                let (kind, target) = spec
                    .split_once(':')
                    .ok_or("--relates takes <kind>:<target>")?;
                relations.push(ClaimRelation {
                    kind: kind.to_string(),
                    target: target.to_string(),
                });
            }
            // Round-tripped through the decoder rather than trusted from the
            // command line, so an unknown kind is refused here exactly as it
            // would be arriving off a peer's log.
            let relations = relations
                .iter()
                .map(|r| ClaimRelation::from_value(&r.to_value()))
                .collect::<Result<Vec<_>, _>>()
                .map_err(|e| e.to_string())?;
            let claim = Claim {
                objective_id,
                submitter,
                artifact,
                nonce,
                created_at: ts.clone(),
                cites,
                relations,
                signature: None,
            };
            claim.validate().map_err(|e| e.to_string())?;
            let outcome = node.reveal(&claim, &ts)?;
            say!("claim {}", outcome.claim_id);
            say!(
                "  verdict  {}: {}",
                outcome.verdict.status.as_str(),
                outcome.verdict.detail
            );
            say!("  {}", outcome.note);
        }
        "settle" => {
            let outcomes = node.settle_at(&ts)?;
            if outcomes.is_empty() {
                say!("no batch was due");
            }
            for outcome in outcomes {
                say!(
                    "claim {}\n  settled  {}  reward {}  ({})",
                    outcome.claim_id,
                    outcome.settled,
                    outcome.reward,
                    outcome.note
                );
            }
        }
        // Decode a single record and say whether it is admissible, without a
        // log and without writing anything. Useful on its own for checking a
        // record before posting it, and it is the surface
        // `scripts/differential.sh` drives to prove the two implementations
        // classify every record the same way.
        "decode" => {
            let kind = positional.ok_or("decode needs a record kind")?;
            let path = flag("--record").ok_or("decode needs --record <file>")?;
            let value =
                Value::from_json(&read(Some(&path), "a record")?).map_err(|e| e.to_string())?;
            match decode_record(&kind, &value) {
                Ok(id) => say!("ok {id}"),
                Err(reason) => {
                    say!("refused");
                    eprintln!("  {reason}");
                    return Err("record refused".into());
                }
            }
        }
        // Canonicalize one JSON value: the format contract at its narrowest.
        // `scripts/fuzz-differential.sh` drives this on random input, which is
        // where an encoder disagreement shows up before it ever reaches a
        // record.
        "canon" => {
            let path = flag("--input").ok_or("canon needs --input <file>")?;
            match Value::from_json(&read(Some(&path), "a JSON value")?) {
                Ok(value) => say!("ok {} {}", value.digest(), value.canonical_string()),
                Err(error) => {
                    say!("refused");
                    eprintln!("  {error}");
                    return Err("input refused".into());
                }
            }
        }
        "log" => {
            for entry in node.ledger.entries() {
                say!("{:>4}  {:<12} {}", entry.seq, entry.kind, entry.hash);
            }
        }
        "audit" => {
            // `rerun` on by default: re-running the pinned verifiers is the
            // thing that makes an audit an audit rather than a checksum.
            let problems = node.audit(!rest.iter().any(|a| a == "--no-rerun"));
            say!("entries {}", node.ledger.len());
            if let Some(root) = node.ledger.merkle_root() {
                say!("merkle  {root}");
            }
            if problems.is_empty() {
                say!("\nlog verified: chain intact, every settled claim re-verified");
            } else {
                for problem in &problems {
                    say!("  ! {problem}");
                }
                return Err(format!("{} problem(s)", problems.len()));
            }
        }
        "prove" => {
            let seq: u64 = positional
                .ok_or("prove needs an entry sequence number")?
                .parse()
                .map_err(|_| String::from("prove: seq must be a number"))?;
            let proof = node
                .ledger
                .prove(seq)
                .ok_or_else(|| format!("no entry {seq}: the log has {}", node.ledger.len()))?;
            let root = node.ledger.merkle_root().ok_or("the log is empty")?;
            // Never emit a proof this implementation would itself reject.
            proof.check(&root)?;
            let text = proof.to_value().canonical_string();
            match flag("--out") {
                Some(path) => {
                    std::fs::write(&path, format!("{text}\n")).map_err(|e| e.to_string())?;
                    say!("wrote {path}");
                }
                None => say!("{text}"),
            }
            say!(
                "  entry {seq} ({})  height {}  root {}  path {} hashes",
                proof.entry.kind,
                node.ledger.len(),
                cairn_reference::canonical::short(&root),
                proof.inclusion.siblings.len()
            );
        }
        other => return Err(format!("unknown command {other:?}")),
    }
    Ok(())
}

/// Not cryptographically chosen: this is a reference implementation and its
/// nonces protect nothing anybody is paid for. The primary implementation uses
/// the OS RNG.
fn random_nonce() -> String {
    let seed = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    cairn_reference::canonical::digest_bytes(&seed.to_le_bytes())
        .trim_start_matches("sha256:")
        .chars()
        .take(32)
        .collect()
}

/// Decode one record of `kind`, returning its id or why it is inadmissible.
///
/// Signatures are checked here too: a record naming a key it cannot prove is
/// inadmissible, not merely unsigned.
fn decode_record(kind: &str, value: &Value) -> Result<String, String> {
    match kind {
        "objective" => Objective::from_value(value)
            .map(|record| record.id())
            .map_err(|e| e.to_string()),
        "commitment" => Commitment::from_value(value)
            .and_then(|record| {
                record.verify_signature()?;
                Ok(record.id())
            })
            .map_err(|e| e.to_string()),
        "claim" => Claim::from_value(value)
            .and_then(|record| {
                record.verify_signature()?;
                Ok(record.id())
            })
            .map_err(|e| e.to_string()),
        "peer" => PeerRecord::from_value(value)
            .and_then(|record| {
                record.verify_signature()?;
                Ok(record.id())
            })
            .map_err(|e| e.to_string()),
        // Structure as well as signature: a share at x = 0 is the secret itself
        // wearing a share's clothes, and a commitment id of the wrong shape can
        // never name a record. Both are admission rules, so both implementations
        // must refuse the same shapes.
        "committee_share" => CommitteeShare::from_value(value)
            .and_then(|record| {
                record.validate()?;
                record.verify_signature()?;
                Ok(record.id())
            })
            .map_err(|e| e.to_string()),
        other => Err(format!("unknown record kind {other:?}")),
    }
}
